### ISSUE TITLE
Edificio Conectado a un Core

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#10]
En el archivo city.h en la estructura de city_building existe el bool que indica si ese edificio esta conectado a un core(cored). Mi pregunta es si los edificios dentro de una zona núcleo vienen cored por default. Ademas si por cored se entiende que el edifico esta conectado a una red que termina en un núcleo o es vecino a un núcleo mismo. Finalmente, un edificio dentro de un core ya viene conectado con su edificio vecino o nosotros tenemos que hacer esta conexión(dado que hay una sola opción).

**Comment by Ghoeb** [comment]
Lo siento, ahi fallé yo con la documentación. Esa variable indica si el edificio está conectado a un _core_ directa o indirectamente (a traves de una red) y solo toma valor en las rutinas del Judge, por lo que no te sirve.

Respecto a lo último, esas conexiones ya vienen hechas: tu programa no debería hacer cambios en los _cores_

**Comment by Ghoeb** [comment]
De todos modos, si te interesa puedes saber si una zona es core con el campo **core**

**Comment by lhcubillos** [comment]
Hola! Una pregunta respecto a esto. Si corro el programa con el 1x1.txt, y hago un *for* sobre todos los edificios de la única zona civil que hay, imprimiendo en pantalla si está *cored* o no, me aparece que hay 5 de los 8 que no están *cored*. A qué se puede deber esto? Puede ser que no vengan efectivamente conectados los edificios al *core* inicialmente? O es problema mío?
Gracias!

**Comment by Ghoeb** [comment]
Lo que pasa es que **cored** no toma valor en el programa normalmente (es el _judge_ el que lo usa) por lo que al no tener valor, `C` toma lo que esté en esa posicion de memoria, lo cual puede ser interpretado como verdadero o falso.

**Comment by jmdelatorre** [comment]
Pero entonces si estan todos los edificios de la zona conectados a un core cierto? pq me ocurre esto y segun yo por logica de la estrucura no deberia suceder..


<img width="89" alt="screenshot 2016-04-01 20 55 20" src="https://cloud.githubusercontent.com/assets/10604162/14222835/1654c5b2-f84c-11e5-959c-8f4dadb58dde.png">

**Comment by Ghoeb** [comment]
Si... eso está muy mal. Revisalo con el judge, te va a avisar si hiciste una jugada ilegal (eso parece ser)
