### ISSUE TITLE
Fecha entrega Tarea 4

### ISSUE THREAD

**Issue by rlira2** [IIC2133-2016-1/syllabus#100]
¿Existe la posibilidad de que den un poco mas de plazo? ¿Hasta el sábado tal vez?

**Comment by jjsotomayor** [comment]
+1

**Comment by FranLucchini** [comment]
+10

**Comment by Ghoeb** [comment]
Si, les pretendía dar más plazo, pero consideren que también tenemos que tener tiempo para alcanzar a corregir la tarea. Dejemosla hasta el 3 de Julio. Más tarde podrían hacernos morir.

**Comment by Ghoeb** [comment]
Además quizás haya una misteriosa T5. Todo depende de como estemos de tiempo y sus notas.

**Comment by Ghoeb** [comment]
Olvídense si de más plazo para el informe, ya que es eso lo lento de corregir.
