### ISSUE TITLE
Prueba recuperativa

### ISSUE THREAD

**Issue by frodrigueza** [IIC2133-2016-1/syllabus#101]
Van a alcanzar a subir los resultados de la prueba recuperativa antes del examen como para calcular notas?

Gracias!

**Comment by Ghoeb** [comment]
Los resultados de la prueba recuperativa de la T1 ya están subidos, y entiendo que las otras notas ya estaban listas (las tiene Yadran)

**Comment by trencoret** [comment]
Y las notas de la tarea 3?

Muchas gracias!

**Comment by Ghoeb** [comment]
Lo siento, no me puedo comprometer con eso.

**Comment by frodrigueza** [comment]
Alguna noticia de la correccion de la prueba recuperativa?

**Comment by Ghoeb** [comment]
La I3 recuperativa para la I1/I2 las iba a corregir Yadran. Yo entendí que estarían listas esta semana, pero perdimos contacto con él, asi que no sabría decirte. 

Saludos!

**Comment by estebanmino** [comment]
Aún sin noticias?

**Comment by Ghoeb** [comment]
Aún sin noticias.

2016-06-27 17:21 GMT-04:00 Esteban Miño <notifications@github.com>:

> Aún sin noticias?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/IIC2133-2016-1/syllabus/issues/101#issuecomment-228879292>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFElCepymJymXEbzud5Bn4v9hNs8UbwUks5qQD7EgaJpZM4I9Ovx>
> .
>



-- 
*Vicente Errázuriz Quiroga*
