### ISSUE TITLE
Comprobar resultados

### ISSUE THREAD

**Issue by marianoll** [IIC2133-2016-1/syllabus#105]
Quisiera saber si podrías subir un set de h's y w's para saber si mi algoritmo se encuentra cerca de aquellos números (especialmente para el w). Algo asi como
Easy:
N: 1000;  A: 10000; Semilla: 9271;  h: 13000; w: 24500
.
.
.

**Comment by Ghoeb** [comment]
No puedo darles eso ya que los generadores aleatorios son distintos en cada PC. Pero si les puedo dar un par de archivos de ejemplo, pero pocos pq pesan mucho:

[Ejemplo 1](https://github.com/IIC2133-2016-1/syllabus/files/334198/easy_1.txt)

SUM(w) = 1336695670950
SUM(h) = 1329012486375

[Ejemplo 2](https://github.com/IIC2133-2016-1/syllabus/files/334204/easy_2.txt)

SUM(w) = 2043349913982
SUM(h) = 2029732968186

[Ejemplo 3](https://github.com/IIC2133-2016-1/syllabus/files/334207/easy_4.txt)

SUM(w) = 1290508836011
SUM(h) = 1281326259720

**Comment by flargofelix** [comment]
Si no me da la misma solución, pero muy muy cercano a ello obtengo puntaje igual?
Ejemplo 1)
sum(w)=1327487909888
Ejemplo 2)
sum(w)=2027968397312
Ejemplo 3)
sum(w)=1279920439296

**Comment by Ghoeb** [comment]
Tienes menos w que mi solución. Cuando h sumas?

**Comment by flargofelix** [comment]
harto más (cerca de 1.4 veces)

**Comment by marianoll** [comment]
Creo que tienes un problema, el w no debería ser menor al h... creo que no tienes la red a su máxima capacidad
