### ISSUE TITLE
Segmentation fault raro

### ISSUE THREAD

**Issue by diesmori** [IIC2133-2016-1/syllabus#107]
Hola! Borren esto si es muy spoiler:

Tengo parte de mi código que compilaba y corría, pero no estaba haciendo lo que necesitaba por estar comparando mal en un while. Al corregir el error, poniendo a comparar ahora variables de unos struct en vez de los struct mismos, me arroja segmentation fault al ejecutar.

Esta es la parte que involucra la falla. Desde el último print que lee hasta el while de la discordia.

``` C
printf("Esto lo imprime");
Tipo** nombre= malloc(sizeof(Tipo*) * valor1); 
printf("Esto ya no"); 
for(int i=0; i< valor1; i++){
   nombre[i]=NULL;
}
for(int i=0; i<valor2; i++){
   long l1,l2,l3,l4;
   fscanf(f, "%li", &l1);
   fscanf(f, "%li", &l2);
   fscanf(f, "%li", &l3);
   fscanf(f, "%li", &l4);
   Tipo* nombre2= tipo_init(l1,l2,l3,l4, NULL, NULL);
   if(nombre[l2]==NULL){
     nombre[l2]= nombre2;
   }
   else{
     Tipo* t= nombre[l2];
     while(nombre2->l4  <  t->l4){
     ...
     //Por acá actualiza t y hace cosas.
}

```
Antes el while era `while(nombre2  <  t)` Me he entrampado y necesito continuar. Muchas gracias.

**Comment by felix91gr** [comment]
Quizás tienes un null pointer?

Revisa si 'nombre2' es distinto de **null**

**Comment by diesmori** [comment]
Lo es, queda inicializado con los valores l1, l2, l3 y l4.
Seguiré probando variantes

**Comment by felix91gr** [comment]
Y t? Es null?

En todo caso puede el problema sea otro. Puede que estés leyendo memoria que no pertenece a tu programa. Eso puede ser porque en `tipo_init` estés haciendo un `malloc` que no sea del tamaño del `struct Tipo` y por lo tanto el puntero en sí **no es nulo**... pero cuando tratas de leer una parte específica del struct, se cae porque esa memoria no está dentro de la memoria que los mallocs le han entregado a tu programa.
(Te hace sentido? Si es muy enredado puedo tratar de explicarlo mejor).

**Comment by diesmori** [comment]
Ahhhh claro, voy a verlo asi
