### ISSUE TITLE
Prueba

### ISSUE THREAD

**Issue by sebastianfdez** [IIC2133-2016-1/syllabus#108]
Algun ayudante o alguien tiene un .txt y la respuesta correcta. Quiero comprobar que mi programa funciona. Ya probe a mano con unos chicos. 

Saludos

**Comment by vjgardul** [comment]
+1 ayura

**Comment by Ghoeb** [comment]
Hm. Esto no era la idea de la tarea. No hay "respuesta correcta". Pero bueno, queda poco asique les daré uno.

[big_example.txt](https://github.com/IIC2133-2016-1/syllabus/files/345304/big_example.txt)
[big_output.txt](https://github.com/IIC2133-2016-1/syllabus/files/345303/big_output.txt)

SUM(w) = 9890275164
SUM(h) = 9301283394

**Comment by rlira2** [comment]
Puede ser que ese output esté malo?

**Comment by vjgardul** [comment]
a mi me da lo mismo

**Comment by Ghoeb** [comment]
Malo no está, pero no es necesariamente el óptimo. Ese es el output de la solucion que marca el 7. Si tu solucion es mejor que eso, tendrás mas que un 7.

La suma de ambos valores es correcta si segun lo entregado por el programa.
