### ISSUE TITLE
Tiempo de resolver el problema vs tiempo en imprimir la solución

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#109]
Hasta el momento estoy encontrando soluciones (no tengo como saber si son válidas o no) para todas las dificultades. El problema que tengo es que para las hard (|V| = 100.000 |E| = 1.000.000) se demora pocos segundos (< 5s) en encontrar la solución, pero se queda mucho tiempo (varios minutos) imprimiendo la solución en consola. El tiempo que sale en el enunciado (menor a 10 segundos) es considerando el tiempo en que se imprimen los índices en la consola?

**Comment by Ghoeb** [comment]
Yo voy a redirigir el output directo a un archivo, el tiempo es mucho menor con eso.

**Comment by flizana** [comment]
Ah ok. Dejo como printf o fprintf los prints en el código?

**Comment by Ghoeb** [comment]
Da lo mismo mientras salga por `stdout`. 

Yo voy a hacer

```sh
./tuprograma archivodeprueba.txt > output.txt
```

Y luego leeré output.txt. Así que asegurate de que funcione con eso.
