### ISSUE TITLE
Clientes vecinos

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#11]
Al principio del programa, se sabe que los clientes que están conectados a alguna central, ya vienen con el respectivo color. Mi pregunta es, yo al usar la función `city_client_link(c1, c2)` en alguna zona civil (llamémosla `z1`) efectivamente estoy linkeando los dos clientes, ¿El cliente `c2` cambiará su color al color de c1? Si esto es así, el cliente vecino a `c2`, es decir, ¿El cliente que está en la zona vecina a `z1` y que además esta linkeado a `c2`  también cambiará su color, o nosotros tenemos que hacerlo manualmente al linkearlos?

**Comment by Ghoeb** [comment]
La coloración debes hacerla tu manualmente, ya que a la hora de deshacer un link debes revertir los cambios de color producto de esa conexión, y para eso haber registrado que clientes cambiaron de color con el link.

**Comment by flizana** [comment]
Buenisimo! Muchas gracias

**Comment by Ghoeb** [comment]
Dejaré el issue abierto porque es muy importante :blush:
