### ISSUE TITLE
Duda

### ISSUE THREAD

**Issue by jmleighton** [IIC2133-2016-1/syllabus#110]
Tengo una duda:
1) puedo usar mas de una tubería para ir del bodo u al v (asumiendo que el flujo es mayor que cada uno por separado)
2) Si optimizo el costo revisando las aristas activas y revisando si existen aristas entre esos nodos que cuesten menos sujeto al flujo calculado anteriormente. Por ejemplo:
El flujo de A a B optimo es de 50. Hay 2 aristas ntre A y B, la 1 con capacidad 50 y la 2 con capacidad 80.El algoritmo glotón va a elegir la 2. Si luego de terminar la optimizacion del flujo, reviso y busco la arista que menos cueste (para rl ejemplo la 1) tengo el 7?
Muchas gracias

**Comment by Ghoeb** [comment]
1) No, la ruta de cada nodo hacia el origen es única y el grafo debe ser acíclico. Además los flujos de las aristas no se suman: h es la capacidad máxima que podría llegarle a un nodo.

2) El algoritmo glotón puede perfectamente elegir la 1 si sabe que aporta lo mismo que la otra pero con menos costo.

**Comment by jmleighton** [comment]
Pero si pongo la condición de que elija el más cercano a su flujo, obtengo el mismo flujo pero con costo menor. Mi pregunta es si cuenta como minimización de costo (para tener sobre 4 o un 7)?

**Comment by Ghoeb** [comment]
Si logras obtener la verdadera arista menor que te da el mismo flujo, podrás llegar al 7 (si es que lo haces rapido)

El 4 lo tendrás si es que tu h es máximo.
