### ISSUE TITLE
Direcciones de los arcos

### ISSUE THREAD

**Issue by dasenRS** [IIC2133-2016-1/syllabus#111]
Hola,

El grafo es adireccional por lo que un arco (u,v) conecta los nodos "u" y "v" de la misma forma que un arco (v,u). Dado que en el input pueden venir más de un arco que conecten los mismos nodos, mi duda es si esos arcos siempre tienen el mismo origen y destino, o en algunos casos pueden venir intercambiados (osea los arcos que conectan el nodo a con b siempre son (a,b) o puede haber alguno (b,a))... ojala que no.. sería muy latero.

saludos

**Comment by Ghoeb** [comment]
No, si el archivo dice que un arco conecta A con B, entonces el mismo arco tambien conecta B con A.
