### ISSUE TITLE
k y valores de aristas en el árbol

### ISSUE THREAD

**Issue by RAACarmona** [IIC2133-2016-1/syllabus#112]
Estoy un poco complicado con un detalle del enunciado. Conozco el algoritmo que genera el árbol de cubrimiento para un grafo no direccional con valores en las aristas, pero las restricciones sobre h(s) no me quedan claros. En el enunciado dice que teniendo una ruta desde el origen f a un nodo s, la capacidad del nodo es el mínimo de h(f)=k y los valores w de todas las aristas en la ruta. Pero para calcular la ruta, hay que utilizar sólo los valores de las aristas. Mi duda es, si k es menor a los w(e) de todas las aristas que salen del nodo de origen f, se "sobreescriben" los valores w(e) para dichas aristas? O calculamos el árbol normalmente utilizando sólo los pesos de las aristas, y una vez tenido ésto ajustamos los h(s) aplicando el mínimo entre k y los w(e) en la ruta hacia cada nodo?

**Comment by Ghoeb** [comment]
Mira, una propiedad que surje de esa definición de las rutas es que para cada nodo su h es el minimo entre el h del nodo "padre" y el w de la arista que los conecta, entendiendose como nodo padre el que está mas cerca de F (o F mismo).

Los valores de W son inmutables, pero una arista puede tener una capacidad w y al mismo tiempo transportar una cantidad de flujo h, dado por el mínimo entre el h del origen y su w. Entonces tu vas a preferir la arista que tenga mayor h, y en caso de empate, la que tenga menor w.

Se entiende?

**Comment by Ghoeb** [comment]
Exacto. Y si todas son menores a k, eliges simplemente la con mayor w.
