### ISSUE TITLE
test casos borde

### ISSUE THREAD

**Issue by rlira2** [IIC2133-2016-1/syllabus#113]
Existe la posibilidad de que suban un test con respuestas que abarque todos (o la gran mayoría) de los casos bordes que podrían generarse, tanto para max h(v) como para el optimo con min w(e). Sería de mucha ayuda :)

**Comment by Ghoeb** [comment]
Casos borde? Los desconozco. Además, los tests se generan aleatoriamente por lo que no tengo control sobre eso.

**Comment by diesmori** [comment]
aah entonces podría darse que se generen grafos no conexos? Sospecho fuertemente que sí

**Comment by Ghoeb** [comment]
Los grafos van a ser conexos si o si. Quizás si usan mal los parámetros del generador les da uno que no es conexo. Pero los grafos con los que corregiré serán conexos. Garantizado.

**Comment by diesmori** [comment]
Genial, un alivio
