### ISSUE TITLE
Address en vez de value

### ISSUE THREAD

**Issue by diesmori** [IIC2133-2016-1/syllabus#115]
Hola. Tengo un problema con los datos de un arreglo:
Este arreglo sólo guarda números, no hay actualizaciones ni eliminaciones. Pero al imprimir o utilizar los valores del arreglo, me cambia algunos por su dirección en memoria.
He comparado la lista de valores antes de ser agregados al arreglo y la impresión del arreglo mismo, y obtengo lo siguiente:

877	877
714	714
595	595
843	144133728
519	144137616
894	144143072
315	144148288
569	144152336
...
494	143904864
789	144356976
540	144377328
972	0
145	145
866	866
369	369
...

Esto corresponde a los nodos visitados: a la izquierda los datos impresos antes de ser agregados al arreglo, a la derecha los datos impresos desde el arreglo.

Cabe señalar que los datos pasan por una iteración donde se agrega uno a la vez, y siempre de la misma forma.

**Comment by Ghoeb** [comment]
Sospecho que tienes errores de memoria. Que aparece cuando lo corres con valgrind?

**Comment by diesmori** [comment]
Valgrind me dice:

`==5997== Invalid write of size 4
==5997==    at 0x8048935: insert (heap.c:67)
==5997==    by 0x8049003: addAll (main.c:194)
==5997==    by 0x80492C8: prim (main.c:330)
==5997==    by 0x8049377: main (main.c:359)
==5997==  Address 0x437db30 is 0 bytes after a block of size 38,456 alloc'd
==5997==    at 0x402A17C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==5997==    by 0x8049056: prim (main.c:203)
==5997==    by 0x8049377: main (main.c:359)
==5997== 
==5997== Invalid read of size 4
==5997==    at 0x8048811: up (heap.c:31)
==5997==    by 0x8048945: insert (heap.c:68)
==5997==    by 0x8049003: addAll (main.c:194)
==5997==    by 0x80492C8: prim (main.c:330)
==5997==    by 0x8049377: main (main.c:359)
==5997==  Address 0x437db30 is 0 bytes after a block of size 38,456 alloc'd
==5997==    at 0x402A17C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==5997==    by 0x8049056: prim (main.c:203)
==5997==    by 0x8049377: main (main.c:359)
==5997== 

valgrind: m_mallocfree.c:304 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 38504, hi = 71585368.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.
`

Efectivamente he implementado un heap. Pero me llama la atencion que los datos que puse en las columnas es obtenido al final de la iteración. En concreto:

`printf("%li \n",visitados[cantidad-1]->indice);
  }// Fin de una iteración

  //Imprime, en orden, los nodos  desde el origen
  //for(int i=0;i<cantidad;i++)    printf("%li\n",visitados[i]->indice);`

**Comment by Ghoeb** [comment]
Arregla los errores que reporta valgrind y debería solucionarse tu problema. Pruebalo con tests pequeños, los problemas deberían estar igual.

**Comment by diesmori** [comment]
Solucionado :dancers: 
Muchas gracias
