### ISSUE TITLE
Recorreccion T4

### ISSUE THREAD

**Issue by jjsotomayor** [IIC2133-2016-1/syllabus#116]
Estimado, quería saber cuando se podrá recorregir la T4?
Porque paso algo raro con mi tarea, todos los tests dieron PROGRAM CRASH, menos Lunatic que dio el optimo.
Mi numero es 12639192 por si acaso.
Saludos

**Comment by felix91gr** [comment]
Mándale un mail a vicho. Él ve la evaluación del programa.

Ahora mismo estamos con las manos llenas corrigiendo informes y el examen,
pero en algún momento debiera poder ver tu caso.

-- Félix
