### ISSUE TITLE
Notas Examen

### ISSUE THREAD

**Issue by trencoret** [IIC2133-2016-1/syllabus#117]
Hola,

Saben mas o menos cuando van a tener las notas de los exámenes? Para poder programarnos un poco.

Muchas gracias
Tomás

**Comment by Ghoeb** [comment]
Para el viernes. Vayan al DCC a recorregir.

**Comment by trencoret** [comment]
Te mande un mail

**Comment by trencoret** [comment]
A que hora llegamos? 9 - 10 am?

Saludos

**Comment by daquiroz** [comment]
Ojalá pudiesen subir las notas antes!
