### ISSUE TITLE
Modificar estructura stack para que acepte Buildings*

### ISSUE THREAD

**Issue by trencoret** [IIC2133-2016-1/syllabus#12]
Hola, en la como puedo modificar la estructura de stack usada en los sudokus de ejemplo para que pueda almacenarme Buildings en vez de int? Quiero poder definir una stack donde los elementos sean Buildings.

Muchas gracias

**Comment by Ghoeb** [comment]
Pero si el stack es generico o.o

**Comment by trencoret** [comment]
Pude hacerlo al final, tenia problemas de punteros etc. Muchas gracias!
