### ISSUE TITLE
Cantidad de edificios por zona

### ISSUE THREAD

**Issue by lhcubillos** [IIC2133-2016-1/syllabus#13]
Hola! Una pregunta. Hay alguna forma de saber exactamente cuántos edificios tiene cada zona? Sé como se puede hacer en código, pero ahí no sé qué zona corresponde a qué indice. Hay alguna forma de verlo gráficamente? Es para revisar que efectivamente el algoritmo solucionó el problema.

Gracias!

**Comment by Ghoeb** [comment]
Hola! Mira, los indices de las zonas crecen hacia abajo y luego hacia la derecha, pero si quieres puedes modificar el watcher para que imprima el numero de la zona encima.
