### ISSUE TITLE
Watcher

### ISSUE THREAD

**Issue by frodrigueza** [IIC2133-2016-1/syllabus#14]
Se supone que al correr `./solver < tests/easy/1x1.txt | ./watcher` el watcher deberia mostrar los cambios hechos en solver.c de manera asíncrona? en tiempo real? Qué cambios especificamente refleja el archivo watcher.pdf una vez cerrada la ventana del solver? A mi me aparece siempre como el estado inicial

**Comment by Ghoeb** [comment]
El **watcher** recibe primero el estado inicial del problema (tu programa hace `c city_layout_print(layout);` ) y luego una a una las instrucciones comunicadas por tu programa, sea conectar dos clientes ( `c city_client_link_print(...)`) o deshacer la ultima conexión hecha ( `c city_client_link_undo_print(...) ` )

El **watcher** procesa cada una de esas instrucciones y dibuja el estado resultante de llevarlas a cabo, independiente de el estado actual de problema en el **solver**

**Comment by felix91gr** [comment]
Por otro lado, se guarda el pdf al cerrar el watcher (pusiste "ventana del solver", pero asumo que te refieres al watcher). 
Si no se está guardando, puede que no hayas cerrado el pdf. Si no lo has cerrado, el watcher no puede escribir en el archivo.

Saludos!
