### ISSUE TITLE
Seg Fault 11

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#15]
Hola,
Al correr el programa de la siguiente manera ```./solver < test.txt ``` me tira error el siguiente error, Segmentation Fault:11.  Pero al correrlo con valgrind, osea ```valgrind  ./solver < test.txt ``` termina sin error. 
?

**Comment by felix91gr** [comment]
Valgrind tiende a atajar los seg faults cuando no son muy graves.

Cuál es el output de Valgrind? Ahí debiera mencionar algo raro.

**Comment by felix91gr** [comment]
Con lo que quiero decir, ese segfault es de verdad, pero no es muy grave.

**Comment by Ghoeb** [comment]
Al correrlo con **valgrind** éste indica en donde fue que se produjo el error. Por qué no nos mandas lo que imprime valgrind?

**Comment by TheDG** [comment]
Logre decifrar lo que decía valgrind, muchas gracias igual!
