### ISSUE TITLE
Cored

### ISSUE THREAD

**Issue by jmdelatorre** [IIC2133-2016-1/syllabus#16]
Cuales son los edificios que estan cored? o cual es la condicon para que esten Cored?

Por alguna razon me tira que ningun edificio esta cored cunado inicio el layout. A veces me tira solo 1. 

Estare haciendo mal algo yo? O estoy entendiendo mal al definicon de Cored?

**Comment by jmdelatorre** [comment]
Sorry no habia leido una pregunta anterior donde responden esto.

Cored lo ocupa solamente el judge
Con core de Zone se puede saber.

**Comment by Ghoeb** [comment]
Respondido en #10
