### ISSUE TITLE
Comportamiento Extraño Watcher

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#17]
Hola tengo un problema con el watcher:
Les presento la secuencia de mi programa
Estado 1
<img width="480" alt="screen shot 2016-04-07 at 9 32 11 pm" src="https://cloud.githubusercontent.com/assets/8753398/14370928/d4379d00-fd08-11e5-83f0-e807fe2525e4.png">
Estado 2   
<img width="474" alt="screen shot 2016-04-07 at 9 33 01 pm" src="https://cloud.githubusercontent.com/assets/8753398/14370938/e2a81568-fd08-11e5-9e65-49370a911ab0.png">
Estado 3
<img width="474" alt="screen shot 2016-04-07 at 9 34 14 pm" src="https://cloud.githubusercontent.com/assets/8753398/14370945/ecc0bfaa-fd08-11e5-977e-cf6e0433444e.png">
La secuencia de llamadas esta acá( link 11 6 4, UNDO)
<img width="142" alt="screen shot 2016-04-07 at 9 35 54 pm" src="https://cloud.githubusercontent.com/assets/8753398/14370999/5fd023be-fd09-11e5-84f2-d62fc8d2b02a.png">
Mi pregunta es si el UNDO debería hacer este comportamiento(eliminar el color del nodo y dejar el link sin color) ya que claramente este eliminando mas que que la ultima conexión.

**Comment by Ghoeb** [comment]
Chispas, eso no es normal. El watcher al hacer una conexión calcula cuales fueron los nodos que cambiaron de color para dejarlos en blanco en caso de tener que hacer undo. Algo debe estar fallando con eso. Seguro que no lo has modificado?

**Comment by TheDG** [comment]
Seguro, acabo de copiar los archivos originales del watcher a mi proyecto y el comportamiento persigue.

**Comment by Ghoeb** [comment]
Dime, que dice el judge de esa secuencia de movimientos? El watcher se corrompe cuando haces una jugada ilegal, mientras que el judge te avisa.

**Comment by TheDG** [comment]
<img width="821" alt="screen shot 2016-04-09 at 3 29 22 pm" src="https://cloud.githubusercontent.com/assets/8753398/14405546/b04a4f40-fe67-11e5-9405-00f877716631.png">

**Comment by TheDG** [comment]
Adicionalmente me di cuenta que la secuencia que city_client_link_print(b1,b2) no es lo mismo que city_client_link_print(b2,b1), cosa que tiene grandes implicaciones para cuando usamos el judge #18

**Comment by TheDG** [comment]
El problema que estoy teniendo con el judge lo describo acá #18(cuando corro el watcher con la lista de instrucciones que le daría el judge)
