### ISSUE TITLE
Duda Judge

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#18]
Para correr correctamente el judge hay que entregar los links en orden secuencial(siempre ir conectando nodos con color) o se pueden dar los links en forma aleatoria?

**Comment by Ghoeb** [comment]
Se pueden dar de forma aleatoria (:

**Comment by TheDG** [comment]
Hola, estoy teniendo problemas con el judge. Cuando corro los test me da el error: Cliente sin color. Para verificar esto corro el watcher con las instrucciones que le daría al Judge. Los mapas se resuelven(queda todo conectado como debería) pero no se propagan los colores. Un ejemplo de esto: 
<img width="486" alt="screen shot 2016-04-09 at 4 43 21 pm" src="https://cloud.githubusercontent.com/assets/8753398/14405994/8753a298-fe72-11e5-90c2-1d7f6d1c61f7.png">
Posterior:
<img width="479" alt="screen shot 2016-04-09 at 4 44 04 pm" src="https://cloud.githubusercontent.com/assets/8753398/14405996/8c4fd32a-fe72-11e5-8660-e9b8fa69e62b.png">
Al conectar una cadena de lineas sin color a un core, envés de propagar el color del core, el core toma el color nulo de las lineas.(por decía que si importaba el orden que se entregan los links)
<img width="200" alt="screen shot 2016-04-09 at 4 45 44 pm" src="https://cloud.githubusercontent.com/assets/8753398/14406012/cca2dd00-fe72-11e5-9cac-bd5efbde0b36.png">
Esos son los links que esta leyendo el watcher, estoy casi seguro que están todos bien
