### ISSUE TITLE
Uso de Judge

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#19]
Hola! 
Relacionado con el comentario anterior (de @Ghoeb en #17), como usamos el judge para saber en que secuencia en específico se esta haciendo una jugada ilegal. Ya que como sale en la pauta pareciera que solo revisa el mapa final. 
Gracias!

**Comment by Ghoeb** [comment]
No, funciona igual que el watcher, como está explicado en #14 , primero se lee el estado inicial del problema, y luego procesa jugada por jugada. Si alguna de estas jugadas es ilegal lo avisa y corta la ejecución. Luego de procesar todas las jugadas revisa si el estado es una solución válida o no e imprime el resultado.

**Comment by estebanmino** [comment]
Ya perfecto, gracias!
