### ISSUE TITLE
Builings con Index altos

### ISSUE THREAD

**Issue by jmdelatorre** [IIC2133-2016-1/syllabus#20]
Hola!

Mi programa me tira segmentation fault siempre que trabajo con buildings con indeces grades (numeros mas de 100) y encuentro raro que existan buildings con indices mayores a 8 siendo que no hay zonas con mas de 8 buildings.

Estare haciendo yo algo mal? 

gracias

**Comment by jmdelatorre** [comment]
tambien me sale linked count = 3 y si imprimos todos los indices al principio ninguno supera el 7

**Comment by gadlewinsohn** [comment]
me pasa lo mismo :(

**Comment by Ghoeb** [comment]
Si linked_count = 3 para un cliente normal entonces están en problemas, ya que estos admiten como maximo 2 vecinos. En caso de intentar conectarle otro vecino más se agregará al arreglo aunque no quepa: evaluará la siguiente dirección de memoria, comiendose la información de otra variable dentro o fuera del struct. Un clásico ejemplo de corrupción de memoria. Prueba a ver que te dice el judge, pero eso parece ser. 

La función que conecta dos clientes no verifica que sea una jugada válida ya que tu ya deberías estar haciendo eso en tu algoritmo para generar las posibles opciones, por lo que añadiría tiempo de ejecución innecesariamente. Esto está advertido en la documentación.

Prueben su programa con el judge y me confirman si era lo que les dije :whale:

**Comment by jmdelatorre** [comment]
Ahi agrege más restricciones para conectarse y mejoro.. pero ahora me sigue tirando errores raros.

Por ejemplo pongo un print  a building[i]->linked y lo imprime correctamente pero en la siguiente linea hago un if con la misma informacion y me tira segmentation fault.

Alguna idea de porque puede estar pasando esto?

**Comment by Ghoeb** [comment]
Cual es exactamente el print que funciona y el if que no funciona?

**Comment by jmdelatorre** [comment]
```
           printf("linked count %i \n", a->zone->buildings[b]->link_count);
            if (a->zone->buildings[b]->link_count < 2) {
```
tal cual :(

**Comment by Ghoeb** [comment]
Estas seguro que se cae al revisar la condicion del if y no al ejecutar lo que está adentro?

**Comment by jmdelatorre** [comment]
si pq tengo un print justo despues del if y no lo ejcuta jajaja es rarisimo

**Comment by felix91gr** [comment]
Mételo a una variable. Imprime la variable y luego ponla en el if. Veamos qué pasa c:

**Comment by jmdelatorre** [comment]
corriendo
```
            printf("linked count %i \n", a->zone->buildings[b]->link_count);
            int c = a->zone->buildings[b]->link_count;
            printf("linked count  alternativo %i \n", c);
            if (c < 2) {
                printf("asd1 \n");
                ....
               }
            else { printf("pasa al else");
             }
```
imprime

```
linked count 2 
linked count  alternativo 2 
zsh: segmentation fault  ./solver < tests/easy/3x3.txt

```

**Comment by Ghoeb** [comment]
Hm, asi por ser, has `make clean` y luego `make`, y luego vuelve a probar tu programa. 

Por cierto, `link_count` es de tipo `uint8_t` por lo que el formato para imprimirlo es `%hhu` y no `%i`, pero no creo que eso sea el problema.

**Comment by felix91gr** [comment]
Ok, vamos al extremo. Hay que probar que la variable permite hacerle operaciones.

Revisa si puedes hacer estas 2 cosas:

```c
c = c + 1
bool d = c < 2

**Comment by jmdelatorre** [comment]
El make clean no me funciona, me tira
`/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [cleanobj] Error 2
`

al probar lo que me dice felix, ahora me tira error en un if anterior (osea el error no los tira en esas lineas)

yo creo que gg nomas :(

**Comment by Ghoeb** [comment]
Hm. Elimina la carpeta obj completamente y todos los archivos compilados y vuelve a hacer make.

**Comment by felix91gr** [comment]
Prueba lo que dice vicho. Está prohibido rendirse :smile:

**Comment by Ghoeb** [comment]
Exacto. Yo no duermo hasta que solucionemos esto.

**Comment by jmdelatorre** [comment]
jajaja probe eliminado los archivos compliados y nada

cuando agrege lo que dijo el felix se cae siempre que revisa que el building al que me quiero mover no sea el mismo que estoy parado. No se como agregando esas dos lineas caga antes jaaja.

**Comment by Ghoeb** [comment]
D: ! No tengo idea que puede ser. Prueba con lo siguiente: guarda lo que tienes ahora y empieza a escribir tu solución otra vez, y vas viendo poco a poco que lo que agregas está funcionando. Ahi deberias poder detectar de donde viene el problema que parece no ser el link_count mismo.

**Comment by jmdelatorre** [comment]
dale :)

gracias por la ayuda igual

**Comment by Ghoeb** [comment]
Por lo demás, la librería tiene funciones que se encargan de ver los datos de un cliente, como 

```c
city_client_is_taken(Client* client);
```

que indica si ese cliente ya ha conectado todos los vecinos que puede. (Si lo niegas significa que "el cliente está disponible" )

**Comment by jmdelatorre** [comment]
sip si lo usaba pero me tiraba el mismo error

**Comment by Ghoeb** [comment]
Debes haber tenido alguna corrupcion de memoria en algun otro lado. Prosigue con armar denuevo la solucion.
