### ISSUE TITLE
Informe inspirador

### ISSUE THREAD

**Issue by flargofelix** [IIC2133-2016-1/syllabus#21]
Hola! Si no me equivoco la Belen había dicho que iban a subir un informe como para guiarnos. Donde está? Y si aun no lo suben podrían hacerlo por favor? Gracias!

**Comment by felix91gr** [comment]
Disculpa la demora. No se subirá un informe *perfecto*, pero sí subiremos 2 (o quizás 3) informes satisfactorios, con notas del corrector. Así podrán ver errores clásicos de los informes y detalles que los mejoran.

Esperamos tenerlos para hoy!

**Comment by felix91gr** [comment]
Ahí subimos el primero de los informes. Espero que antes de mañana tengamos el segundo.
