### ISSUE TITLE
Duda judge 1.2

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#22]
Hola, estoy teniendo problemas con el judge. Cuando corro los test me da el error: Cliente sin color. Para verificar esto corro el watcher con las instrucciones que le daría al Judge. Los mapas se resuelven(queda todo conectado como debería) pero no se propagan los colores. Un ejemplo de esto: 
<img width="486" alt="screen shot 2016-04-09 at 4 43 21 pm" src="https://cloud.githubusercontent.com/assets/8753398/14405994/8753a298-fe72-11e5-90c2-1d7f6d1c61f7.png">
Posterior:
<img width="479" alt="screen shot 2016-04-09 at 4 44 04 pm" src="https://cloud.githubusercontent.com/assets/8753398/14405996/8c4fd32a-fe72-11e5-8660-e9b8fa69e62b.png">
Al conectar una cadena de lineas sin color a un linked[0] de un building de un core, envés de propagar el color del core, el core toma el color nulo de las lineas.(por decía que si importaba el orden que se entregan los links)
<img width="200" alt="screen shot 2016-04-09 at 4 45 44 pm" src="https://cloud.githubusercontent.com/assets/8753398/14406012/cca2dd00-fe72-11e5-9cac-bd5efbde0b36.png">
Esos son los links que esta leyendo el watcher, estoy casi seguro que están todos bien

**Comment by TheDG** [comment]
Este ejemplo explica lo anterior de mejor manera(2x1)!
Prints que le doy al Watcher(o el judge si se quiere).
<img width="101" alt="screen shot 2016-04-09 at 9 30 12 pm" src="https://cloud.githubusercontent.com/assets/8753398/14407312/1053f54e-fe9a-11e5-88ab-5aa8b3dd1f1e.png">
Estado Inicial
<img width="385" alt="screen shot 2016-04-09 at 9 28 48 pm" src="https://cloud.githubusercontent.com/assets/8753398/14407313/18fdf50a-fe9a-11e5-96df-45251e72bf33.png">
Despise  de Link 0 1 4 (osea desde el punto building vacio al nucleo morado)
<img width="385" alt="screen shot 2016-04-09 at 9 28 48 pm" src="https://cloud.githubusercontent.com/assets/8753398/14407317/4db03326-fe9a-11e5-8e73-b6bbcd8bcc7b.png">
Despues del Link 0 6 3 (desde el azul chico al azul grande)
<img width="395" alt="screen shot 2016-04-09 at 9 28 52 pm" src="https://cloud.githubusercontent.com/assets/8753398/14407324/8260a2d6-fe9a-11e5-92e1-032287c5aeb2.png">

**Comment by Ghoeb** [comment]
No estoy logrando reproducir el problema... hago LINK 0 1 4 apenas empieza el solver y no me pasa lo que te pasa a ti en el watcher. No será que estes modificando el mapa de la ciudad antes de imprimirlo? Y por eso el watcher se enreda? :cry:

**Comment by Ghoeb** [comment]
Dime, que pasa si pruebas el judge con el siguiente comando:

```sh
solver < tests/easy/2x1.txt | ./judge tests/easy/2x1.txt
```

Si el problema es lo que digo entonces el Judge debería funcionar como corresponde (:

**Comment by TheDG** [comment]
Hola, difícil que este modificando el mapa antes de imprimirlo ya que ``` /* Leemos la ciudad del input */
    Layout* layout = city_layout_read(stdin);

    /* Lo imprimimos para darle el estado inicial al watcher / judge */
    city_layout_print(layout);
``` son mis primeras lineas de código. 
Al correr ```solver < tests/easy/2x1.txt | ./judge tests/easy/2x1.txt```me da el siguiente error:Cliente sin color: ZONA 0 CLIENTE 0.
Cuando corro el programa en modo Judge lo que hago es hacer pop del stack de decisiones y para luego hacer ```client_link_print(base,next)```Cada Pop es un Building parte del Link(por ende se hacen dos pops). Lo interesante es al hacer el como client_link_print(next,base) ```solver < tests/easy/2x1.txt | ./judge tests/easy/2x1.txt```no me tira error alguno

**Comment by Ghoeb** [comment]
Espera... estás notificando las conexiones dos veces? Porque cuando se lee un `city_client_link_print(C1,C2)` simplemente se llama `city_client_link(C1,C2)`, y llamar esa funcion dos veces debería corromper el puzzle (quizas el judge no lo detecta?)

**Comment by Ghoeb** [comment]
Cuando yo corro tu secuencia de conexiones me funciona perfecto. Lo único distinto entre tu judge y watcher con los que estoy usando yo (que son los que subí) es el `city.h` que usan. No deberia dar problemas si modificaste los structs, pero anda a saber. Que tal si haces una copia de los originales para que trabaje el watcher y judge y ves si hay alguna diferencia?

**Comment by TheDG** [comment]
Podia ser algo en el CMakeList?? Estoy usando el city.h original y corriendo el siguiente comando 
```
/* Leemos la ciudad del input */
    Layout* layout = city_layout_read(stdin);

    /* Lo imprimimos para darle el estado inicial al watcher / judge */
    city_layout_print(layout);
    printf("LINK %zu %hhu %hhu\n", 0, 4, 1);
```
y todavia tengo comportamiento extraño. (Estoy usando el city_io.c y city.h originales)

**Comment by Ghoeb** [comment]
Qué es CMakeList?

**Comment by TheDG** [comment]
Porfin! Fui cambiando archivo por archivo hasta el original para detectar cuando el comportamiento se volvía loco! Yo propagaba los colores dentro del city.c (ósea al hacer city_client_link(a,b) dentro del mismo método ponía el código pertinente). Esto cambiaba el comportamiento inicial del mapa(se me olvido que city_io también usaba city_client_link). Me quiero matar

**Comment by Ghoeb** [comment]
Jajaja diosmio, bueno al menos descubriste que era. Mi intención en todo momento fue que modificaran solo city.h, porque al modificar los .c de ahi no tienes idea quien está usando las funciones y quien no, por lo que podian pasar cosas como esta :cry:. Ánimo con lo que queda! Si quieres ayuda para propagar los colores puedes revisar como lo hace el judge :whale:
