### ISSUE TITLE
Modificar Estructura Building

### ISSUE THREAD

**Issue by dacasas** [IIC2133-2016-1/syllabus#23]
Hola, cuando quiero modificar la struct de city_building, agregandole algunos componentes, no me arroja ningun problema, pero cuando las inicializo, me arroja errores de lectura del grafo ("Error leyendo grafo"), aveces uno y otras dos, y al final un "Segmentation Fault (Core Dumped)". Intente inicializar estas en city_io.c, ya que ahi es donde se inicializan las demás y también en el solver.c directamente, pero ambas me arrojaban los mismos errores. Alguna idea?

**Comment by Ghoeb** [comment]
Hola c:
Qué estas agregando y como lo inicializas?

**Comment by dacasas** [comment]
Agrego un arreglo de buildings y un contador para el arreglo, y los inicializo asi:
Por cada building hago:
building->contador = 0; //contador es un uint8_t
building->arreglo = malloc(sizeof(Building*) * building->zone->building_count);// arreglo es de tipo Building**(son dos asteriscos, esque github me lo toma como uno parece jaja)
Y lo intente inicializar identicamente a como se hace con el arreglo linked y link_count, pero en la parte donde ya estaban inicializadas las zonas, para poder hacer la referencia a la cantidad de edificios de la zona.

**Comment by Ghoeb** [comment]
Ya, y como inicializas lo el resto de "arreglo"? Pregunto por que si te pasas o lo usas mal puedes sobreescribir otra parte del struct.

**Comment by dacasas** [comment]
como? esque segun yo nunca me pasaré, porque a lo más hay 8 o 4 edificios por zona, pero este puede ser el problema jaja

**Comment by Ghoeb** [comment]
Cuando se te cae? Con estas lineas de código? Correlo con valgrind y te va a salir donde es.

**Comment by dacasas** [comment]
Parece ser que es lo que dijiste, valgrind me arroja:
- Use of uninitialised value of size 8
- Invalid read of size 8
- Address 0x700000007 is not stack'd, malloc'd or (recently) free'd
- Access not within mapped region at address 0x700000007

**Comment by dacasas** [comment]
Como puedo arreglarlo?, intente con un realloc(), aumentendo al doble el tamaño, pero me siguio arrojando los mismo errores y en la misma direccion de memoria incluso.

**Comment by Ghoeb** [comment]
El punto es que inicializaste el arreglo, pero cada celda está en blanco. Si intentas trabajar con ella se va a caer.

**Comment by dacasas** [comment]
Con que esta en blanco te refieres a que habria que iniciarlo con NULLs?, poque eso también lo intente al ver como se hace con linked, pero tampoco me funciono :(

**Comment by Ghoeb** [comment]
Si no le has dado valor, entonces iniciamente tiene pura basura adentro, por lo que te va a dar segfault o comportamiento inesperado (ya que esa basura es distinta en cada ejecucion). Que es lo que pretendes guardar en ese arreglo?

**Comment by dacasas** [comment]
Las opciones que tendra el building para conectarse, pero tambien podrian ser los indices de las opciones, aunque no creo que cambie mucho el problema, porque lo intente tambien y es igual.

**Comment by Ghoeb** [comment]
Hm, y que tal si en lugar de usar ese arreglo y ese contador, usas un heap? Con eso simplemente insertas opciones (tendrias que vaciarlo antes de insertar nada) y además puedes elegir en que orden salen (significa que podrías meter una heuristica entremedio)

**Comment by dacasas** [comment]
Si algo asi habia pensado, pero quería hacer un caso mas básico primero, pero voy a intentarlo nomas. Gracias!
