### ISSUE TITLE
Building_count en Cores

### ISSUE THREAD

**Issue by alopez7** [IIC2133-2016-1/syllabus#24]
Trabajando ayer me di cuenta de que en los mapas con cores de muchas entradas, el building_count de esos cores es siempre 1, lo cual está mal, y hace que mi programa funcione mal también.
¿Alguien puede corroborar esto o es cosa de mi programa?

**Comment by Ghoeb** [comment]
Está bien, lo que pasa es que efectivamente una zona core tiene un solo building (una Central), pero este building tiene varias conexiones hacia las celdas vecinas, entre 0 y la cantidad de lados de la zona. Puedes saber cuantos puertos tiene con 

```c
city_core_get_capacity(Core* core)
```
