### ISSUE TITLE
Problema al descolorear (undo)

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#25]
Al hacer undo tengo previo al llamado de `city_client_link_undo` el siguiente código:

    Building* ret = stack_pop(stack);
    if(city_client_is_taken(ret))
    {
        ret -> linked[1] -> color = 0;
        ret -> linked[1] -> linked[0] -> color = 0;
        city_client_link_undo(ret, ret -> linked[1]);
        city_client_link_undo_print(ret, ret -> linked[1]);
    }
    undo_count++;
    return ret;

Pero, al probar el código con el watcher, y veo que un una conexión se deshizo, los clientes siguen con el mismo color de antes. No se si el problema es de punteros o si puedo cambiar los colores de esta forma

**Comment by Ghoeb** [comment]
No has modificado ninguna funcion de la librería?

**Comment by flizana** [comment]
solo modifique la funcion `city_client_link` para que al linkear dos clientes estos queden con los mismos colores.

**Comment by TheDG** [comment]
yo tuve ese problema caleta de rato! cambia los colores afuera del city_client_link en el solver :)

**Comment by flizana** [comment]
Buena! Eso me sirvió
