### ISSUE TITLE
Duda funciones para linkear

### ISSUE THREAD

**Issue by dacasas** [IIC2133-2016-1/syllabus#27]
Hola!, leyendo algunos issues anteriores, en uno decía que el city_client_link_print(a,b), imprime en consola el link efectuado, y además hace city_client_link(a,b), cosa que ví también cuando me metí a ver el watcher (drawer.c). Pero desde un principio lo que yo hacía era efectuar el link (city_client_link(a,b)), y además hacer el print (city_client_link_print(a,b)), y me funciona hasta ahora bastante bien, aunque con algunos errores extraños, que creo que se deben a esto. Cuando fui a modificar mi codigo para que solo hiciera el print, el watcher se comporta mucho mas extraño haciendo unas pocas conexiones y nada mas. A que se podría deber esto?, ya que supuestamente al hacer el print, debería hacer el link posteriormente o no?, pienso que quizás es un desfase con la velocidad a la que ejecuta el watcher y mi codigo, pero no estoy muy seguro. Y si es que no se usan así los link y print, cual es la forma correcta de usarlos? Gracias de antemano por leer la pregunta un poco larga jaja.

**Comment by Ghoeb** [comment]
Hm, habrás modificado la funcion city_client_link(a,b) ?

**Comment by dacasas** [comment]
Emm, no no he modificado esa funcion, pero ahora me esta funcionando bien el watcher, era un error mio. Pero aun sigo llamando a las dos funciones para efectuar el link, eso esta mal o no?

**Comment by Ghoeb** [comment]
No, no, esta bien, asi es como se deberían usar.

**Comment by dacasas** [comment]
Aaa ya perfecto esa era mi duda principalmente jaja
Muchas Gracias!
