### ISSUE TITLE
Desconectar clientes 

### ISSUE THREAD

**Issue by LeFranck** [IIC2133-2016-1/syllabus#28]
Hola, tengo problemas al desconectar dos clientes. Ya que necesito desconectar dos clientes en especifico, no los ultimos que conecte. El judge me dice que los clientes estan conectados, aun cuando uso el  city_client_link_undo(c1,c2), donde en ambos su ultima conexión fue entre ellos. Cualquier ayuda u orientación es bienvenida. 
En estas imagenes se puede apreciar el problema
[3x3.pdf](https://github.com/IIC2133-2016-1/syllabus/files/213920/3x3.pdf)
[sol.pdf](https://github.com/IIC2133-2016-1/syllabus/files/213921/sol.pdf)

**Comment by Ghoeb** [comment]
Pero, tanto el judge como el watcher asumen que el UNDO se refiere a la ultima conexion hecha, sin clientes en especifico, dado que estamos trabajando con backtracking no deberías querer deshacer una desición que no sea la ultima que se efectuó.

**Comment by LeFranck** [comment]
Estoy haciendo backtracking sobre como llenar el mapa, no sobre la ultima conexión. 
Digase, trato de conectar todas las centrales, si lo logra sigue, si no me devuelvo.
Una vez todas conectadas, desconecto algun link y trato de resolverlo sin ocupar este link previo. (Donde se puede ver un glitch en la red). Esto proceso anda bien cuando lo corro con el valgrind y watcher (Dado que no se cae al leer mal la desconexión). 
[5x5.pdf](https://github.com/IIC2133-2016-1/syllabus/files/214079/5x5.pdf)

**Comment by Ghoeb** [comment]
Pero eso no es backtracking. La libreria entera está construida para que resuelvas tu problema usando backtracking. Si quieres puedes usar el metodo de tu preferencia, y puedes usar las funciones de la librería, pero no vas a poder comunicarte con el watcher dado que los mensajes de undo deshacen la ultima decision tomada. Si logras rellenar completamente el puzzle, si puedes pasarle las decisiones al judge para que las evalue, pero no vas a poder debugear.

**Comment by Ghoeb** [comment]
Ahora, si quieres puedes modificar la funcion de undo_print para que imprima CUAL es la conexion que debe deshacer y arreglar eso en el watcher...

**Comment by felix91gr** [comment]
Por otro lado, si no usas backtracking tu informe no será evaluado. En éste se pide expliquen sus heurísticas y podas, y que analicen su rendimiento con los tests.

Si quieres usar otra técnica, por favor ten esto en cuenta.
