### ISSUE TITLE
Desconectar clientes 

### ISSUE THREAD

**Issue by LeFranck** [IIC2133-2016-1/syllabus#29]
Hola, tengo problemas al desconectar dos clientes. Ya que necesito desconectar dos clientes en especifico, no los ultimos que conecte. El judge me dice que los clientes estan conectados, aun cuando uso el  city_client_link_undo(c1,c2), donde en ambos su ultima conexión fue entre ellos. Cualquier ayuda u orientación es bienvenida. 
En estas imagenes se puede apreciar el problema

[3x3.pdf](https://github.com/IIC2133-2016-1/syllabus/files/213937/3x3.pdf)
[sol.pdf](https://github.com/IIC2133-2016-1/syllabus/files/213939/sol.pdf)

**Comment by Ghoeb** [comment]
#28
