### ISSUE TITLE
Error al compilar (fatalerror: gtk/gtk.h: No such file or directory)

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#3]
Hola,

Tengo un problema al hacer el Setup en Ubuntu. Seguí al pie de la letra las indicaciones que nos entregaron. Al parecer todo funcionaba bien hasta que intententé compilar en donde me apareció el error mencionado en el título de la issue.

Entré a la carpeta en donde se encuentra gtk.h (/usr/include/gtk-3.0/gtk/) y en esta se encontraba el archivo. Al parecer no se puede encontrar a pesar de que hice la configuración (export LD_LIBRARY_PATH=/usr/include/gtk-3.0/).

Si alguien me puede guiar sería de mucha ayuda ya que llevo algunas horas tratando de solucionar el problema.

Muchas gracias!

**Comment by Ghoeb** [comment]
Hola! Cual es el error que lanza en la compilación? 

Por lo pronto, puedes editar el programa y donde dice

```c
#include <gtk/gtk.h>
```
poner 

```c
#include <gtk-3.0/gtk/gtk.h>
```

Avisame como te va

**Comment by estebanmino** [comment]
Cambié el archivo como dijiste pero sigue lanzando el mismo error. 
Adjunto una captura de pantalla del terminal.

Gracias por la ayuda!

![error](https://cloud.githubusercontent.com/assets/12115171/13658459/e0c772a8-e655-11e5-82c7-924c2633d46d.png)

**Comment by Ghoeb** [comment]
Bueno gdk != gtk. 
Además cambiaste de lugar los archivos, y la Makefile depende de eso. Necesito que clones el repositorio, y de ahi una vez adentro de la carpeta `HelloGTK` escribas simplemente
```sh
make
```
para saber bien qué está pasando.

Además, dime por favor cual es el resultado de correr el comando
```sh
pkg-config --cflags --libs gtk+-3.0
```

**Comment by estebanmino** [comment]
Funcionó perfecto, antes de sacar los archivos de la repo estaba haciendo la compilación al interior de /HelloGTK/src sin razón alguna.

Muchas gracias por la ayuda!
