### ISSUE TITLE
Informe en latex

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#32]
Una pregunta básica, cómo puedo agregar el logo de la uc, junto con el texto Escuela de Ingeniería, Departamento, etc, antes del título
Tengo esto en latex

    \title{Informe Tarea 1}
    \author{Mi nombre}
    %\date{}

    \begin{document}

**Comment by Ghoeb** [comment]
Oh, yo tengo un macro para eso, deja buscarlo y te lo mando (:

**Comment by Ghoeb** [comment]
Ok ahi armé un pequeño template, pero me está fallando mandarlo por aqui, asique lo subi a la carpeta [Tareas/Informes de Ejemplo/Template](https://github.com/IIC2133-2016-1/syllabus/tree/master/Tareas/Informes%20de%20ejemplo/Template) :3

**Comment by Ghoeb** [comment]
Quizas tenga un par de paquetes que no sean necesarios jaja es la acumulación de cosas que he ido necesitando a lo largo de los años.
