### ISSUE TITLE
Problemas en OSX

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#34]
Estoy consciente de que hay un error para correr la librería en OSX. Lamento el inconveniente. Espero tener la versión corregida mañana Sabado 23, pero son ustedes los que tendrán que decirme si realmente se arregló el problema dado que no tengo OSX a mi disposición.

Por mientras pueden buscar videos en YouTube donde se explica Raytracing y como mejorarlo, o buscar algun _paper_ respecto al uso de estructuras de **jerarquía espacial**.

Saludines :whale:

**Comment by flizana** [comment]
Vicente, yo logré correr el código base, el programa me dejó este output:

    MacBook-Pro-de-Fernando-5:programa fernandolizana$ ./raytracer ./scenes/easy/cube.scene 2 -f
    Rendereando 12 triángulos
    La escena tiene 8 puntos en total
    Computación finalizada en 0.575089 segundos

Pero luego, se dibujó un cuadrado blanco en la pantalla y hasta ahí llegó. No sé si ya está corregido o no, pero así se ve:

![img_error_osx](https://cloud.githubusercontent.com/assets/6475823/14763503/91f30594-096d-11e6-99db-81248a4d1637.png)

**Comment by Ghoeb** [comment]
Si, eso de la pantalla en blanco es exactamente el problema al que me refiero :disappointed:

**Comment by Ghoeb** [comment]
Ok, ahi lo corregí. Pruebalo ahora ;)
