### ISSUE TITLE
Respecto a las Bounding Boxes y su intersección

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#35]
Si bien dije que incluiría estas funciones en el código, me equivoqué al decir que usabamos esa función en nuestra solución, por lo que lo que sea que les subamos no tendría ninguna garantía de funcionar.

Les pido disculpas, pero dejaré que implementen ustedes su propias funciones para trabajar con Bounding Boxes.

Saludines! :whale:

**Comment by estebanmino** [comment]
Hola! Tengo varias dudas con respecto a esto y lamentablemente no pude ir ayer a hablar con ustedes. 

Primero como obtengo las dimensiones de las scenes, para poder hacer lo que explicaron el Lunes en la ayudantía, lo máximo que encontre fué el ancho y alto de la imágen, que me imagino que es del output del programa.

Segundo, en las instrucciones sale que solo podemos modificar solution/manager.c y solution/manager.h pero en solution/scene.h sale textualmente "Eres libre de modificar el output de sus funciones ", cuál es el objetivo de este comentario? Quizás ahí deberíamos implementar funciones relacionados con bounding boxes?

Gracias!

**Comment by Ghoeb** [comment]
"Eres libre de modificar el output de sus funciones" significa que puedes modificar lo que sea que esas funciones te hayan entregado cuando las llames, no modificar la funcion en si o su firma. En particular se refiere a que no hay problema con que desordenes los arreglos de puntos o de triángulos. Si los sobreescribes o eliminas podrían generarse problemas en la memoria, pero lo demás está permitido.

Respecto a tu otra duda, cuando hablamos de la caja que envuelve un conjunto de vertices hablamos de la caja mas pequeña tal que todos los vertices están contenidos en ella. Como estamos en 3 dimensiones, esto se reduce a 6 planos que envuelven a los vertices. Estos planos están especificados cada uno por el menor y el mayor de los vectores para cada componente. En definitiva, el mayor X de todos los vertices, el menor X de todos los vertices, el mayor Y de todos los vertices, y asi. (+X,-X,+Y,-Y,+Z,-Z)

El output del programa es una imagen. Las escenas traen un ancho y un alto, si, pero eso indica las dimensiones en pixeles de las imagenes y no tiene nada que ver con las posiciones de los vertices y triangulos en la escena.

Saludos!

**Comment by adelsol1** [comment]
Respecto a la caja pequeña tengo una duda. Entiendo como encontrar la caja pero no me queda claro donde pongo esos parametros para utilizarla. Se debe ver que rayos pasan por esa caja y descar el resto? o es otra la aproximación?

**Comment by Ghoeb** [comment]
Puedes crear tu propio `struct caja` que represente la caja y escribir una función que indique si una caja dada intersecta con un rayo y donde (ya expliqué porque no subí esas funciones) Lo importante de las cajas es la noción de que si un rayo intersecta con una caja, existe la posibilidad de que intersecte con alguno de los triángulos que esta contiene, pero en caso de que no intersecte, entonces definitivamente podemos descartar esos triángulos para la intersección con ese rayo en particular.

Lo que dices tu es al reves, para cada rayo debo ver las cajas que me sirven y descartar el resto. Jamas debes descartar rayos. Luego, para cada caja posible las pruebo en el orden de la dirección del rayo, y en caso de intersectar con un triángulo dentro de una caja ya sabemos que es el más cercano (si la caja tiene mas de un triángulo debes probar todos esos para poder aseverar que estas chocando con el más cercano) y podemos descartar las demás cajas.

**Comment by Ghoeb** [comment]
Por cierto, el método que te digo para recorrer es a grandes rasgos. En realidad desde el primer momento tienes que ver las cajas en el orden de la dirección del rayo, asi no revisas cajas demás. Una vez que intersectes, retornas y listo.

![traversal](https://cloud.githubusercontent.com/assets/5317897/14959836/5824820e-105f-11e6-886a-39c43ccf1f9e.png)
