### ISSUE TITLE
struct Vertex

### ISSUE THREAD

**Issue by frodrigueza** [IIC2133-2016-1/syllabus#37]
El struct vertex tiene como atributos el vector position y vector normal. 

Podrían aclarar para que sirve el normal? Hubiese pensado que lo único relevante de un vértice de un triángulo es su posición. No es así?

**Comment by Ghoeb** [comment]
Oh, te lo puedo explicar si quieres pero no tiene nada que ver con lo que tienen que hacer en la tarea: ustedes tienen que únicamente usar y entender las funciones que se declaran en los headers en la carpeta `solution`. Por eso no les exponemos el triángulo entero, por que tiene mucha mas informacion que la que ustedes tienen que usar (y ademas no queremos que sean capaces de tocar esas cosas de los triángulos, ya que podrían romper el resto del programa)

El triangulo tiene un material, y sus vértices tienen posición, normal y coordenada de textura. Entre ellos, y la luz y direccion del rayo, se calcula el color de ese triángulo en el punto de interseccion, interpolando los datos de los 3 vertices.
