### ISSUE TITLE
Datos de la cámara

### ISSUE THREAD

**Issue by diesmori** [IIC2133-2016-1/syllabus#38]
Hola! Quisiera saber si contamos con los datos de la cámara y su enfoque: FOV, near, top... Además del origen y direcciones de los rayos.
Me surge esta duda por si existen escenas con triángulos detrás del observador o fuera de su campo visual.

(Quiero poner labels, pero no sé cómo)

**Comment by felix91gr** [comment]
(Nosotros agregamos los labels, es una restricción de Github u.u sería bkn que ustedes pudieran ponerlas)

No cuentan con esos datos porque no los debieran necesitar :)

Me explico: los rayos que se usarán como parámetro en el **manager** no siempre vendrán de la cámara. Algunos serán producto de reflejos, otros de refracción, etc: esos son los *rayos secundarios*. A veces sólo hay una cantidad pequeña y a veces hay una cantidad mucho mayor que los rayos primarios. Depende puramente de la escena y de la posición de la cámara.

Por lo tanto, la estructura que harán ustedes tiene que servir para rayos que viajen en **cualquier dirección** y que tengan **cualquier origen** :)

**Comment by diesmori** [comment]
Genial, entiendo.
Y se pueden obtener los vértices de un triángulo? O cómo asocio un vértice al/los triangulos en los que participa?

**Comment by felix91gr** [comment]
Claro, se pueden obtener los vértices de un triángulo. 
Revisa las funciones de **geometry.h** :)
