### ISSUE TITLE
Triangle* vs Triangle vs Triangle**

### ISSUE THREAD

**Issue by adelsol1** [IIC2133-2016-1/syllabus#39]
Estoy un poco confundida de como tomar el valor de los triangulos. Muchas veces se hace el llamado como Triangle\*\* para un arreglo de Triangle y no entiendo porque son dos \*\* envez de Triangle\*. Tampoco entiendo porque algunas veces se toma Triangle\* y no Triangle

Ejemplos:
solution/geometry.h
```c
 /** Representa un triángulo. */
typedef struct triangle Triangle;
```

modules/scene.h

```c
/** Arreglo con los triángulos de la escena. (largo = face_count)*/
Triangle** faces;
```

solution/scene.h
```c
/** Intenta intersectar el rayo con el triángulo.
    En caso de éxito y que esté más cerca que el triángulo anterior que
    haya intersectado, se almacenarán los datos de la intersección         */
void      ray_intersect               (Ray* ray, Triangle* tri);
```

**Comment by Ghoeb** [comment]
Ya, vamos por partes. Lo primero es lo primero: que son los punteros.

```c
/* Un triángulo */
Triangle A;
/* Un puntero a un triángulo */
Triangle* B;
/* Un puntero a un puntero de triángulo */
Triangle** C;
/* Un puntero a un puntero a un puntero de triángulo*/
Triangle*** D;
```

Los punteros son direcciones de memoria donde hay guardado un objeto del tipo especificado. Cuando uno solicíta la memoria, pide un trozo de tamaño igual al tamaño del objeto para poder guardarlo (por eso es `malloc(sizeof(objeto))`). 

La gracia es que nada nos restringe a la cantidad de memoria que podemos solicitar para guardar un objeto. Esto es especialmente útil para declarar arreglos de largo dinámico (determinado en tiempo de ejecución), donde en lugar de pedir un trozo de memoria para un solo objeto, solicitamos de una sola vez, en memoria contigua, memoria para guardar `n` objetos. (por eso es `malloc(sizeof(objeto) * n)`). Luego podemos acceder a cualquier elemento del arreglo usando los corchetes de toda la vida. El compilador sabe de que tipo es el arreglo, y por lo tanto hace el salto en memoria del largo correspondiente.

En el caso del código de la tarea, se les da un arreglo de punteros a triángulo, dado que ustedes en su codigo solo saben que existen los triángulos, pero no saben por que están compuestos. Al no saber eso, es imposible que uses en tu codigo `Triangle` a secas, tiene que ser un puntero. Eso es simplemente para que tengan que preocuparse de entender solo lo que involucra el problema, ya que los triangulos tienen MUCHA mas información que solo los vértices. Por lo tanto, la libreria te ofrece los punteros a triángulo y no los triángulos en si, ya que los punteros son solo direcciones de memoria y tu parte del código sabe trabajar con eso. Para poder ver los detalles del triangulo que a ustedes les interesan fue que construí la funcion `void triangle_get_vertices(Triangle* tri, Vector* v1, Vector* v2, Vector* v3);`

Por cierto, que haces mirando el scene.h de la carpeta modules? El código fuera de la carpeta solution no está pensado como para que ustedes lo tengan que entender...

Dime si te quedan dudas. Saludos!

**Comment by frodrigueza** [comment]
Creo que esto 
`objeto* varios = malloc(sizeof(objeto) * n);`
debería decir:
`objeto** varios = malloc(sizeof(objeto) * n);`

O no?

**Comment by adelsol1** [comment]
Ahi me quedo mucho mas claro gracias! Estaba revisandolo para entender un poco mas la estructura para crear las mias propias o.O
 Otra duda es la funcion de ` void vector_add_v (Vector* v, Vector w) `
Porque el primero es un puntero al vector y el segundo es el vector mismo..? que pasa si tengo dos punteros a vectores y quiero sumarlos?
Mi intencion es guardar los punteros a los vectores q representan un triangulo via` void triangle_get_vertices(Triangle* tri, Vector* v1, Vector* v2, Vector* v3);`
y luego sacar el promedio para encontrar el centroide y es mas facil usando vector_add_v.

Gracias!

**Comment by felix91gr** [comment]
Felipe: 
> Creo que esto
> `objeto* varios = malloc(sizeof(objeto) * n);`
> debería decir:
> `objeto** varios = malloc(sizeof(objeto) * n);`
> O no?

Un `objeto*` es en este caso un arreglo de elementos de tipo `objeto` (porque es un puntero al primer `objeto` del arreglo), por lo que dentro del malloc ponemos **`sizeof(objeto)`** por la cantidad de elementos (`n`).

Por otro lado un `objeto**` sería una matriz, si lo queremos usar como un arreglo de arreglos. En ese caso hacemos `sizeof(objeto*)` porque es un arreglo de elementos de tipo `objeto*`, por el alto de la matriz. Después para cada elemento i-ésimo hacemos malloc con `sizeof(objeto)`, por el ancho de la matriz.

Una mnemotecnia fácil de recordar es que si tienes una variable que es por ejemplo `int*...* a`, la cantidad de pasos de `malloc` que debes hacer para inicializar un int que `a` referencia, es la misma cantidad de asteriscos que `a` tiene en su declaración. Por ejemplo, si es `int* a`, entonces con 1 malloc inicializas el arreglo y `a[i]` es un elemento de `a`. Si es `int** a`, entonces con 1 malloc inicializas un arreglo de `int*` y luego con un for haces 1 llamada a malloc por cada uno y con eso luego puedes acceder a un elemento de a (que es un arreglo de arreglos) haciendo `a[i][j]`.

**Comment by felix91gr** [comment]
Alicia:
> Otra duda es la funcion de ` void vector_add_v (Vector* v, Vector w) `
> Porque el primero es un puntero al vector y el segundo es el vector mismo..? que pasa si tengo dos punteros a vectores y quiero sumarlos?

En la librería `vectors.h` hay dos funciones para sumar vectores, las 2 suman pero de forma distinta:

`void vector_add_v(Vector* v, Vector w)` suma `v` con `w` y deja el resultado guardado en `v`. Necesita un puntero a `v` para poder modificar el valor que está guardado en la referencia.

`Vector vector_added_v(Vector v, Vector w)` suma `v` con `w` y retorna el resultado. Ya que retorna el resultado, no necesita un puntero porque te lo entrega directamente.

La verdad es que puedes usar cualquiera de los 2, según lo que te acomode. A mí me acomoda usar más el segundo, porque es más como yo me lo imagino.

No pasamos los punteros (excepto en el caso del `Vector* v` en `vector_add_v`) por dos razones:
- Es más eficiente usar el struct directamente (porque no hay que leer el puntero y luego ir a la memoria que referencia; se lee el struct y listo).
- Si pasamos un puntero la función podría modificar el valor guardado en la referencia. Para encapsular mis variables, yo preferiría no darle el puntero a la función si no que darle una copia nomás :)

**Comment by Ghoeb** [comment]
Por cierto, si bien la funcion para leer los vértices de los triangulos solicita `Vector*`, eso no significa que en tu codigo los hayas tenido que declarar usando malloc. Piensa que esa función la vas a estar usando constantemente dentro de la construcción del arbol. Es mucho mas simple y eficiente decir
```c
/* Declaramos los vectores por valor en el stack de memoria */
Vector v1,v2,v3; 
/* & obtiene la direccion de memoria de un elemento, &x es un puntero que apunta a x */
triangle_get_vertices(tri, &v1, &v2, &v3); 
/* Ahora v1 v2 y v3 tienen guardados los vertices del triangulo */
```

**Comment by diesmori** [comment]
Se puede hacer la operación inversa? Es decir, dado un vértice obtener el o los triángulos a los que pertenece.

**Comment by Ghoeb** [comment]
No. Imposible. Podrías implementarlo pero seria O(n) en la cantidad de triángulos.

**Comment by diesmori** [comment]
Entonces debo buscar otra forma de armar mi árbol? Porque ordenar los vértices no tiene sentido si luego no puedo saber a qué triángulos involucra.

**Comment by Ghoeb** [comment]
Si tiene sentido. Puedes recorrer la lista de triángulos para ver cuales son menores al pivote y cuales mayores (y cuales quedan cortados por él). Luego repites el proceso para las sublistas de triangulos + vértices.
