### ISSUE TITLE
intersección rayos con cajas

### ISSUE THREAD

**Issue by josehj** [IIC2133-2016-1/syllabus#40]
hola! 
Tengo el problema de que no entiendo el como funciona la dirección del rayo. En este momento tengo construidas las cajas y puedo compararlas con los orígenes de los rayos, sin embargo no se como puedo ver con cual intercepta al extender su dirección y ver cual es la primera caja entre todas las  con que choca.

Si me pudiesen señalar como se comporta la dirección o en que archivo de la tarea verlo seria lo mejor :)

**Comment by Ghoeb** [comment]
El rayo representa una recta vectorial, es decir, tiene un punto de origen _p_ y un vector unitario _d_ que es su dirección. Todos los puntos de esta recta se pueden escribir como _p + td_ donde _t_ es un número real. Usando eso puedes resolver la ecuación de intersección con los planos de la caja para obtener los puntos de intersección en caso de existir. Si t = 0, entonces estamos en el punto. Si t < 0 significa que estamos yendo hacia atras, por lo que la intersección no cuenta. Si t > 0 entonces estamos yendo hacia adelante. En caso de que el rayo intersecte con la caja entonces la cruza en dos puntos: el punto de **entrada** y el punto de **salida**. 

Para saber con cual caja intersectas primero basta con intersectar con las cajas y comprar los puntos de entrada del rayo a la caja. La caja con el punto de entrada más cercano al origen del rayo es la que está más cerca, por lo que es la que querrás revisar primero.

**Comment by TheDG** [comment]
Hola!
Actualmente mi solución corre mas lento que la solución tonta(mátame). Tengo un presentimiento que esto puede ser por la función intersect(rayo,caja). Es possible rehusar tu función que intersect(rayo, triángulo)?

**Comment by Ghoeb** [comment]
Copia el codigo si quieres, pero si te anda más lento no creo que eso lo arregle, el problema debe estar en otro lado. Revisa:

* Cuando estas dejando de dividir (Esto regula la profundidad  del arbol y a cantidad de triangulos por nodo (segun tu metodo))
* La profundidad del arbol generado (si tienes que bajar mucho es posible que al final ande mas lento)
* La cantidad real de triangulos en cada hoja (porque si estas revisando la lista entera cada vez no te va a servir de nada)

Igual mañana voy a estar para que resolvamos dudas.
