### ISSUE TITLE
Ayudantia Viernes 06

### ISSUE THREAD

**Issue by adelsol1** [IIC2133-2016-1/syllabus#42]
Hola a que hora y donde van a estar hoy? Gracias!!

**Comment by Ghoeb** [comment]
Al menos entre 14:00 y 17:00, pero quizás llegue antes y / o me vaya después :yum:

**Comment by Ghoeb** [comment]
En el DCC pues. No podemos asegurar una sala, pero siempre hay algun espacio para trabajar :ok_hand:
