### ISSUE TITLE
Lectura escenas

### ISSUE THREAD

**Issue by jmdelatorre** [IIC2133-2016-1/syllabus#48]
Hola,

Las escenas se leen de la misma manera siempre? Pueden los triangulos estar en distinto orden cada vez que corro mi programa?

Lo digo porque a veces me tira segmentation fault ( no se exactamente donde), a veces me carga la figura, y a veces me carga la figura pero despues de un rato crashea.

Lo Raro es que solamente estoy cargando el arbol nada mas, y el ray tracing deberia emepzar una vez que ya carge la figura, por lo que es raro que se caiga despues de haber cargado el arbol correctamente.

gracias

**Comment by felix91gr** [comment]
Los triángulos son ofuscados en el orden, es decir, antes de crear el manager la librería desordena los triángulos que tiene en el Triangle** que entrega. Si estás asumiendo alguna cosa respecto del orden en que vienen los triángulos, puede que ahí tengas un error.

Sin embargo, una vez entregados los triángulos, la librería no modifica dicho arreglo.

Lo que me tinca que tienes es que dentro de tu árbol, en alguno o varios nodos tienes un "triangle count" incorrecto. Entonces cuando lo cargas no pasa nada (porque estás escribiendo las listas de triángulos de los nodos), pero cuando lo lees intentas leer más allá de lo que hay en los nodos (pues el count incorrecto te lo permite). Eso causaría un *segmentation fault* después de cargar el árbol, pero no durante.

Dime cómo te va con esto.

**Comment by jmdelatorre** [comment]
Pucha, cada vez que corto la lista de triangulos paso como argumento la cantidad de elementos triangulos que tiene mi nueva lista, entonces no deberia estar sobrepasandome o leyendo triangulos que no existen :(

**Comment by felix91gr** [comment]
Pon prints del tamaño de tus listas, y pon variables que cuenten cada vez que asignas un triángulo en un arreglo. Algo no debe de estar calzando.

**Comment by jmdelatorre** [comment]
eso mismo hago, cuando recorro por mi nuevo arreglo recorro por la cantidad de triangulos que le asigne, numero que siempre sera igual o menor que el del arreglo

**Comment by jmdelatorre** [comment]
de hecho, lo mas raro que me ocurre es que la imagen se renderea (sin usar mi optimizacion) pero despues me tira error

```
Rendereando 12 triángulos
La escena tiene 8 puntos en total
Computación finalizada en 5.228071 segundos
zsh: segmentation fault  ./raytracer ./scenes/easy/cube.scene 5
```

Osea, lo unico que trato de hacer es inizializar mi arbol pero nisiquiera lo ocupo para hacer mas rapido el rendering

**Comment by felix91gr** [comment]
Ahh, se te cae al liberar el árbol. Me tinca que le estás haciendo free dos veces al mismo puntero, yo me armé el mismo error cuando lo hice.

**Comment by jmdelatorre** [comment]
mejoro en la cantida de segmentation fault que me tira, pero de 5 2 siguen siendo segmentation fault :(

**Comment by Ghoeb** [comment]
Pero, que esta pasando con los triangulos repetidos? Piensa que a la hora de dividir los triangulos, te van a quedar dos grupos que lo mas probable es que sumen mas triangulos que el grupo original, ya que algunos los tuviste que mandar a ambos lados...

**Comment by jmdelatorre** [comment]
Sip, pero el arreglo sigue siendo mayor (asume q se pueden repetir todos) y la cantidad de triangulos calcula si hay repetidos... :(

van a estar mañana o el viernes en la U para poder revisar bien el codigo?

**Comment by Ghoeb** [comment]
Si claro. Mira, para probar por mientras (este cambio es solo para debugear. recuerda que vamos a corregir usando solo tu carpeta solucion) 

Anda a src/modules/scene.c y comenta las lineas 565 y 566 (las llamadas a shuffle). Ve si cambia el comportamiento de tu programa al desactivar la ofuscacion.
