### ISSUE TITLE
Error al leer escenas

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#49]
Las siguientes escenas presentan errores:
Billiards

    Error reading file: assets/materials/billiard.mtl
    Error reading file: assets/mesh/plane_y.obj

Infinicandy

    Error reading file: assets/materials/candy.mtl
    Error reading file: assets/mesh/nordehasoci.obj

Metallic

    Error reading file: assets/materials/metal.mtl
    Error reading file: assets/mesh/metal_plate.obj

Starters

    Error reading file: assets/materials/starter.mtl
    Error reading file: assets/mesh/metal_plate.obj

Lucy

    Error reading file: assets/materials/lucy.mtl
    Error reading file: assets/mesh/fancy_floor.obj

**Comment by felix91gr** [comment]
Baja el repo de nuevo, te falla igual?

También pon en qué OS estás. Puede que sea un tema de los paths.

**Comment by Ghoeb** [comment]
Revisa la carpeta assets. Estan esos archivos ahi?

**Comment by flizana** [comment]
Faltaban los archivos de la carpeta assets. Gracias
