### ISSUE TITLE
Error Make Ayudantía 2

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#5]
## Hola :)
Tengo un Problema al hacer el Make de la Ayudantía 2.
Soy Usuario de OSX. 
No tuve problemas al hacer make sobre la ayudantía 1 o los programas de ejemplo.
Al hacer make en Ayudantía2/Programas me da el siguiente error:

<img width="425" alt="screen shot 2016-03-23 at 4 38 49 pm" src="https://cloud.githubusercontent.com/assets/8753398/13998370/a424c6a0-f115-11e5-9491-ffc1aef22738.png">

Adicionalmente al abrir el proyecto con CLion me da el siguiente error:

<img width="965" alt="screen shot 2016-03-23 at 4 58 26 pm" src="https://cloud.githubusercontent.com/assets/8753398/13998943/81187bae-f118-11e5-844b-af9ba4c6bdf1.png">

Gracias por cualquier ayuda

**Comment by Ghoeb** [comment]
Dado que no tengo un Mac a mi disposicion no puedo revisar el error, pero claramente esta fallando el comando mkobj, encargado de crear los directorios obj. Dado que en realidad ese comando solo es necesario una vez, puedes hacer lo siguiente:

* Junto a la carpeta src, crea una carpeta llamada obj.
* Dentro de obj, crea carpetas con los mismos nombres que las carpetas dentro de src
* Abre la Makefile. Reemplaza la linea que dice

```sh
all: mkobj $(PROGRAMS)
```

por 

```sh
all: $(PROGRAMS)
```

Avisame como te va c:

**Comment by Ghoeb** [comment]
Modifiqué esa operación para el Makefile de la Tarea 1, espero que ahora les funcione :whale:

**Comment by TheDG** [comment]
Gracias :)!

**Comment by Ghoeb** [comment]
Efectivamente lo arreglaba! Asi que subí la version corregida para la Ayudantía 2. Saludoskis
