### ISSUE TITLE
triangle_get_vertices vs importar modulo

### ISSUE THREAD

**Issue by TheDG** [IIC2133-2016-1/syllabus#50]
Hola,
Para acceder a los vértices de un nodo envés de ocupar la función dada( triangle_get_vertices()) importe "/modules/geometry.h" a manager.h.
Hasta el momento me funciona bien. Mi duda es hay algún problema con usar esta metodología, o deberíamos solamente usar la función triangle_get_vertices().
Atte,
Diego

**Comment by Ghoeb** [comment]
Hm... importa solo el geometry.h que está en la carpeta solution. Deberia funcionar con eso.
