### ISSUE TITLE
Illegal Instruction:4 al hacer malloc

### ISSUE THREAD

**Issue by trencoret** [IIC2133-2016-1/syllabus#51]
Nose por que al momento de hacer el primer malloc de algo me tira ese error. Tengo importada la `#include <stdlib.h>`. Esta llamada se hace al inicializar desde el manager al KdTree, llamando a una funcion del kdtree.c.

`KdTree* tree = malloc(sizeof(KdTree));`

Estuve buscando en internet por harto rato y no logre encontrar una solución. Alguien más tiene el mismo problema?

**Comment by Ghoeb** [comment]
Chuta, dame el detalle porque asi como está no puedo ayudarte :s

**Comment by trencoret** [comment]
Tendría que postear mi código aca, te lo pregunto mañana en la u mejor?

Gracias

**Comment by Ghoeb** [comment]
OK.

**Comment by trencoret** [comment]
@Ghoeb Avisame cuando llegues, yo estoy en la Alvaro Campos!
