### ISSUE TITLE
Valgrind

### ISSUE THREAD

**Issue by jmdelatorre** [IIC2133-2016-1/syllabus#52]
Alguna idea de porque no funciona valgrind?
usando OSX el captian

el error: http://pastebin.com/UkQwiC8M

filo ahi pude arreglarlo pero me salen estos errores
Error 1:
`0x00007fff99cf84e9 in objc_msgSend () from /usr/lib/libobjc.A.dylib
`
Error 2:
`[Switching to Thread 0x1e17 of process 19743]
0x00007fff8b13bf06 in __pthread_kill () from /usr/lib/system/libsystem_kernel.dylib
`

Error 3:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fff8c4027f5 in CGClipStackGetBounds () from /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics

```

**Comment by Ghoeb** [comment]
Hola. Yo adverti de que quizas valgrind no diera los resultados esperados en OSX. No puedo hacer mucho al respecto, la version para OSX aun es muy nueva...

**Comment by jmdelatorre** [comment]
tendria que correrlo en ubuntu??

en todo caso esos errores que puse los saque con gdb no con valgrind

**Comment by Ghoeb** [comment]
Si. A tu valgrind no le gustó el codigo de LibPNG parece xD
