### ISSUE TITLE
Verificación de la solucion

### ISSUE THREAD

**Issue by josehj** [IIC2133-2016-1/syllabus#54]
Hola,
quería saber si están publicados en alguna parte los tiempos que tienen que demorarse cada imagen y como deberían quedar estas. ¿Se usa el structure_test para revisar eso? Y si es posible ¿pueden subir las imágenes listas para compararlas con las que nos salen :)?

Gracias

**Comment by Ghoeb** [comment]
Las imagenes listas ya están subidas. Para revisar los tiempos cuenta la cantidad de rayos que le llegan a tu estructura y compara eso con el tiempo total de rendereo. De cuanto es la mejora?
