### ISSUE TITLE
Condición ingenua de término de construcción del KDTree

### ISSUE THREAD

**Issue by RAACarmona** [IIC2133-2016-1/syllabus#57]
Al construir el KDTree, tenemos una condición de término ante la cual se deja de subdividir el árbol y el nodo en el cual se trabaja se define como hoja. A futuro pienso implementar un criterio SAH (surface area heuristic), pero en primera instancia estoy buscando un funcionamiento más simple (naïve/ingenuo)  considerando sólo profundidad o cantidad de triángulos. Considerando esto, y relativo al valor conocido de total de triángulos en la escena, que profundidad del árbol (ej. profundidad máxima 6, 7, 8) o proporción de triángulos presentes en la hoja prospectiva (2⁻⁷, 2⁻⁵, otra orden de magnitud?) podría ser un buen criterio inicial para trabajar? Disculpas si este tipo de preguntas no es permitida.

**Comment by Ghoeb** [comment]
Eso tienes que verlo tu a la hora de analizar el arbol para tu informe. Que pasa si trabajas una cantidad relativa a la cantidad maxima? Que pasa si trabajas una cantidad constante independiente de la cantidad maxima de triangulos? :yum:
