### ISSUE TITLE
Segmentation fault con scene_get_triangles

### ISSUE THREAD

**Issue by flargofelix** [IIC2133-2016-1/syllabus#58]
Hola!
tengo el problema que me está apareciendo segmentation fault. Ocurre cuando llamo a 
Vector* v1;
 Vector* v2;
 Vector* v3;
triangle_get_vertices(manager->triangles[0],  v1, v2, v3);
Lo raro es que antes ya cargo los datos necesarios con:
manager -> triangle_count = scene_get_triangle_count(scene);
manager -> triangles = scene_get_triangles(scene);
Al parecer scene_get_triangles(scene) retorna un array vacio.
Alguna idea de que pueda ser?

**Comment by Ghoeb** [comment]
```c
Vector* v1;
Vector* v2;
Vector* v3;
```
No están inicializados: inicialmente son NULL. Claramente te va a tirar segmentation fault si es que tratas de asignarles algo. Mi recomendacion es usar

```c
Vector v1,v2,v3;
triangle_get_vertices(manager->triangles[i], &v1, &v2, &v3)
```

**Comment by flargofelix** [comment]
Buenisimo! Muchas gracias :)
