### ISSUE TITLE
Tarea 1 - Make inicial - fatal error: 'gtk/gtk.h' file not found

### ISSUE THREAD

**Issue by frodrigueza** [IIC2133-2016-1/syllabus#6]
Hola, hice clone del repo y cuando hago make en Tarea1/Programa/ me tira el siguiente error:

MacBook-Pro-de-Felipe:Programa felipe$ **make**
_Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
clang: warning: -lm: 'linker' input unused
In file included from src/watcher/drawer.c:1:
src/watcher/drawer.h:4:10: fatal error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^
1 error generated._

Uso OSX El Capitan y ya instale homebrew gtk+-2.24.30

**Comment by Ghoeb** [comment]
Oh pero en las guias de setup dice que estamos usando GTK+ 3, no el 2, por eso falla.

**Comment by frodrigueza** [comment]
**brew install gtk+3** resolvio el problema. Muchas gracias
