### ISSUE TITLE
Escenas Hard Informe

### ISSUE THREAD

**Issue by rlira2** [IIC2133-2016-1/syllabus#61]
En el último ítem del desglose para realizar el informe, se indica que para obtener todo el puntaje se deben usar escenas "Hard". Sin Embargo solo hay carpetas con escenas "Normal" y "Lunatic". ¿Cual deberíamos usar?

**Comment by felix91gr** [comment]
Todavía no hemos subido escenas Hard.

Por el momento estamos testeando las que hemos construido. Esperamos subir al menos 3 el miércoles, con esas debieran tener suficiente para trabajar en ese ítem.

Idealmente habrán 4 o 5 escenas Hard en total.

**Comment by alopez7** [comment]
Aún no hay escenas hard, se puede hacer esa parte con las escenas lunatic que funcionen en un tiempo razonable?

**Comment by Ghoeb** [comment]
Si, o sino tambien sirven las normales. Mientras te corra y puedas hacer comparaciones, está bien.

**Comment by alopez7** [comment]
Pero en el enunciado dice que hay descuento si usamos las normales

**Comment by Ghoeb** [comment]
Si a estas fechas aun no están las escenas hard no hay otra alternativa.
