### ISSUE TITLE
Buenas practicas?

### ISSUE THREAD

**Issue by frodrigueza** [IIC2133-2016-1/syllabus#63]
Existe alguna buena practica para lograr que mi programa corra siempre de la misma manera? Por alguna razón, seguramente por mala administración de la memoria, este se cae en distintos lugares cada vez que lo corro. También hay veces que corre perfecto y dibuja lo que quiero.

Si existen estas buenas prácticas, podrían listarlas?

Gracias

**Comment by Ghoeb** [comment]
Si, existe un lista de buenas practicas, pero el hecho de que tu programa corra siempre distinto es porque al inicio del programa los triángulos se revuelven. Eso quiere decir que la funcion que elige el plano divisor debe estar fallando y hace que te salgas del arreglo en algunas ocasiones. Ponle prints a todo y usa el structures_test con valgrind.
