### ISSUE TITLE
Triangles

### ISSUE THREAD

**Issue by jmleighton** [IIC2133-2016-1/syllabus#64]
Cuando voy armando el arbol recursivamente, voy separando los triangulos** en triangulosDerecha y triangulosIzquierda de la siguiente forma:
                
                  ......
                    triangle_get_vertices(triangulos[i],&p1, &p2, &p3);
                    if(condicion )
                    {
                      triangIzq[jTriangIzq] = triangulos[i];
                      jTriangIzq ++;
                    }

                    else if(condicion)
                    {
                      triangDer[jTriangDer] = triangulos[i];
                      jTriangDer ++;
                    }
                    else
                    {
                      triangDer[jTriangIzq] = triangulos[i];
                      triangIzq[jTriangDer] = triangulos[i];
                      jTriangIzq ++;
                      jTriangDer ++;
                    }
             El tema es que a medida que va bajando el arbol, algunos triangDer[i] o triangIzqu[i] son NULL, es normal eso? Estoy controlando ese error pero quiero saber si es normal.

**Comment by Ghoeb** [comment]
Que raro, no debería haber punteros nulos entremedio.

**Comment by jmleighton** [comment]
Alguna idea de porque puede pasar?

**Comment by Ghoeb** [comment]
Cual es el tamaño original de tus arreglos?

**Comment by jmleighton** [comment]
El arreglo inicial es del porte de la cantidad de triangulos que entrega la
escena. Luego con un contador para cada nodo (derecha e izquierda) los
separando. Los triangulos que tienen puntos en ambos lados de la mediana
quedan guardados en ambos arreglos (obviamente también incrementa el
contador para ambos nodos en este caso). luego entrego el tamaño de los
arreglos al crear los nodos derecha e izquierda recursivamente.

2016-05-19 16:48 GMT-04:00 Vicente Errázuriz <notifications@github.com>:

> Cual es el tamaño original de tus arreglos?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IIC2133-2016-1/syllabus/issues/64#issuecomment-220443304>
>



-- 
Saludos
José Manuel Leighton

**Comment by Ghoeb** [comment]
```c
else
{
     triangDer[jTriangIzq] = triangulos[i];
     triangIzq[jTriangDer] = triangulos[i];
     jTriangIzq ++;
     jTriangDer ++;
}
```

Estas accediendo al arreglo con los indices cambiados

**Comment by jmleighton** [comment]
Bueena jajaj no me habia dado cuenta 

José Manuel Leighton
