### ISSUE TITLE
Fecha de entrega Tarea02

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#65]
Hola, 
Hay alguna fecha aproximada de la entrega de la tarea? Para poder organizarnos con el tema del informe y proyectos de otros ramos.
Muchas gracias!

**Comment by jmdelatorre** [comment]
y otra cosa, como sera la evaluacion finalmente? si los hard son los lunatic, entonces hacer los normal y easy vale mas de la mitad del puntaje cierto?

**Comment by Ghoeb** [comment]
El punto de darles este plazo adicional era la incertidumbre de la fecha de entrega.

La evaluacion se mantiene igual: cada set de tests vale lo mismo. Aun no están listos los hard.

**Comment by trencoret** [comment]
Cuando es el tiempo maximo para correr un scene? Si me corren los hard de ahora pero en 80-120 segundos, no se consideraran? Gracias

**Comment by Ghoeb** [comment]
Calcula cuanto es la mejora de los test easy y normales y extrapola eso a las demás. Cual es la funcion de n que determina el tiempo de ejecucion?

**Comment by Ghoeb** [comment]
Con la funcion me refiero a que el tiempo debería ser
```
t(n) = m * f(n) * k

n = cantidad de triángulos
m = cantidad de rayos
f(n) = funcion asociada a la busqueda de intersecciones: f(n) = n en el caso por fuerza bruta.
k = constante asociada a tu computador
```
