### ISSUE TITLE
Testing Informe

### ISSUE THREAD

**Issue by rlira2** [IIC2133-2016-1/syllabus#66]
En el ítem de testing se nos pide lo siguiente:
Sea, dada una escena y el comportamiento del programa al generar su imagen:
◦ t = el tiempo en generar la imagen
◦ q = la cantidad de rayos generados
◦ n = la cantidad de triángulos de la escena
Sea entonces t’ = t / (q x n)

Tengo dudas respecto a "q", ya que el tiempo en generar la imagen y la cantidad de triángulos de la escena vienen dados como output en consola al correr el programa. ¿Cómo podemos saber que valor toma "q"? o a que se refiere exactamente?

**Comment by Ghoeb** [comment]
La funcion del manager que recibe un rayo se llama una vez por rayo, por lo que puedes contar cuantas veces se llama esa funcion para saber la cantidad de rayos que hubo.
