### ISSUE TITLE
"Error reading file"

### ISSUE THREAD

**Issue by dasenRS** [IIC2133-2016-1/syllabus#67]
recien le hice pull al repo del curso para probar la escena sponza (que no la tenia antes). Copié mi carpeta solution y remplaze la que venia del repo, ahora me salen estos errores (antes no tenía ningún problema con lucy y ahora si). 

dasen@dasen-Lenovo-G400s:~/Desktop/dasenRS-iic2133-repo/Tareas/Tarea02/Programa$ ./raytracer ./scenes/lunatic/lucy.scene 1 
Error reading file: assets/mesh/lucy_floor.obj
dasen@dasen-Lenovo-G400s:~/Desktop/dasenRS-iic2133-repo/Tareas/Tarea02/Programa$ ./raytracer ./scenes/lunatic/sponza.scene 1 
Error reading file: assets/materials/sponza.mtl
Error reading file: assets/mesh/sponza.obj
*** Error in `./raytracer': double free or corruption (out): 0x000000000230cc50 ***
Aborted (core dumped)

que hago?? ayura

**Comment by Ghoeb** [comment]
Copia y pega por completo la carpeta assets a tu repo

**Comment by dasenRS** [comment]
Es que tome toda la carpeta de la tarea (del repo del curso) y le cambie la carpeta solution por la mia...
asi que assets es la del repo

**Comment by Ghoeb** [comment]
Pero... borraste la anterior antes de pegar? Porque hay archivos que se llaman igual y son distintos.
