### ISSUE TITLE
Error con lunatic/dragon

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#69]
Hola,
Al correr *lunatic/dragon.scene* me sale el error *Unknown tag in scene: NST*, siendo que *lunatic/lucy.scene* y *lunatic/sponza.scene* me corren bien sin ningún error. 
Es un error de mi programa? A alguien mas le ha pasado?
Gracias!

**Comment by rlira2** [comment]
A mi me pasó lo mismo

**Comment by Ghoeb** [comment]
Tuve que hacer unos cambios en el codigo base... copien y peguen las carpetas src/raytracer y src/modules para arreglarlo.
