### ISSUE TITLE
Error al compilar tarea 1

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#7]
Estoy trabajando en OSX, ya he instalado gtk+3 y gtk+, pero al ejecutar `make` en el directorio programa me sale lo siguiente

    Package xcb-shm was not found in the pkg-config search path.
    Perhaps you should add the directory containing `xcb-shm.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'xcb-shm', required by 'cairo', not found
    clang: warning: -lm: 'linker' input unused
    In file included from src/watcher/drawer.c:1:
    src/watcher/drawer.h:4:10: fatal error: 'gtk/gtk.h' file not found
    #include <gtk/gtk.h>
         ^
    1 error generated.
    make: *** [obj/watcher/drawer.o] Error 1

Otra pregunta que no encontré en las guías, ¿Cuáles son los pasos a seguir para poder correr el programa?

**Comment by Ghoeb** [comment]
Hm, instalaste GTK+ según las instrucciones de la guía? La idea del setup y los programas de ejemplo era solucionar todo este tipo de problemas antes de que empezaran las tareas.

Necesito que me digas el resultado de correr este comando en la terminal:

```sh
pkg-config --cflags --libs gtk+-3.0
```

**Comment by flizana** [comment]
Sí, lo instalé según la guía. Esto me sale como output del comando de arriba

    Package xcb-shm was not found in the pkg-config search path.
    Perhaps you should add the directory containing `xcb-shm.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'xcb-shm', required by 'cairo', not found

**Comment by Ghoeb** [comment]
Bueno y que hay de instalar el `xcb-shm` ? Revisa si está en homebrew.

**Comment by flizana** [comment]
Finalmente pude solucionar el problema agregando el directorio al PATH:

    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
