### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by diesmori** [IIC2133-2016-1/syllabus#70]
Para armar mi árbol llamo recursivamente a un método que particiona en dos los triángulos y los vectores, y en su interior creo nuevos arreglos con malloc: por ejemplo  `arreglo = malloc(cantidad_de_elementos+1 * sizeof(Triangle*));`

Al correr el programa, entra bien al método varias veces (unas 20). Tiene condiciones de parada que se ven gracias a algunos printf. Pero tras algunas recursiones arroja segmentation fault.

He leído bastante al respecto, y dudo que esté pidiendo demasiada memoria en los malloc, ni entrando tantas veces al método. No hago free() porque necesito los arreglos que voy creando.

No se me ocurre qué puede ser. Me tiene entrampado y he avanzado muy lento porque cada vez doy con errores que me tardo horas en zanjar lidiando con C.

**Comment by Ghoeb** [comment]
Y qué dice valgrind al respecto? Pruebalo con structures_test

**Comment by diesmori** [comment]
No me deja hacer structures_test, pero haciendo memcheck tengo lo siguiente:

HEAP SUMMARY:
==12713==     in use at exit: 25,460 bytes in 240 blocks
==12713==   total heap usage: 285 allocs, 45 frees, 29,968 bytes allocated

Y tras varios cuadros de detalles:

LEAK SUMMARY:
==12713==    definitely lost: 0 bytes in 0 blocks
==12713==    indirectly lost: 0 bytes in 0 blocks
==12713==      possibly lost: 2,484 bytes in 83 blocks
==12713==    still reachable: 22,976 bytes in 157 blocks
==12713==         suppressed: 0 bytes in 0 blocks
==12713== Reachable blocks (those to which a pointer was found) are not shown.
==12713== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==12713== 
==12713== For counts of detected and suppressed errors, rerun with: -v
==12713== ERROR SUMMARY: 83 errors from 83 contexts (suppressed: 0 from 0)

He tratado de entender qué significa, pero no me queda claro dónde está el problema.

**Comment by frodrigueza** [comment]
Ojo con los parentesis
