### ISSUE TITLE
Fecha entrega informe

### ISSUE THREAD

**Issue by jmdelatorre** [IIC2133-2016-1/syllabus#71]
Existe la posibilidad de entregar el informe un poco mas adelante? 

Seria muy bien bienvenido en especial por el tiempo dedicado a la tarea :)

gracias

**Comment by favazquez** [comment]
+1

**Comment by eiurrutia** [comment]
+1

**Comment by gadlewinsohn** [comment]
+1

**Comment by felipebaitelman** [comment]
+1

**Comment by josehj** [comment]
+1

**Comment by diesmori** [comment]
++

**Comment by Ghoeb** [comment]
Yo no quería dejar la entrega para el lunes para que fueran a la ayudantia de la T3, así que haremos lo siguiente: Pueden entregar EL INFORME

**Comment by flizana** [comment]
Vicho, ¿No será una mejor idea que aquellos que asistan a la ayudantía puedan entregar el informe a las 23:59?

**Comment by gadlewinsohn** [comment]
+1

**Comment by jmdelatorre** [comment]
apoyo a lizana, no tiene mucho sentido dejar la fecha del informe dependiendo de cuantos llegan a la ayudantia, yo no tengo como controlar lo que hace el resto. 

y ademas, yo no puedo ir mañana a la ayudantia, y siento que estoy perjudicando a mis compañeros...

**Comment by Ghoeb** [comment]
Bueno ya.
