### ISSUE TITLE
Hora entrega Tarea02

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#72]
Hola,
El commit del enunciado de la Tarea03 me sale que fué hace 11 horas, podrían especificar la hora de entrega por favor? 
Hasta ahora estoy considerando como hora de entrega a las 1:00 AM (24 hrs. después de la entrega del enunciado), y no quiero tener problemas con este tema.
Muchas gracias!

**Comment by felix91gr** [comment]
Hola!
La Belén hará el fetch a primera hora del lunes, es decir, t > 6am. Espero que no sea necesario, pero pueden aprovechar esas horas si es que les hacen falta :)

**Comment by estebanmino** [comment]
Perfecto! Gracias!
