### ISSUE TITLE
Límites T3

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#76]
Para que puedan abusar de ellos, les dejo los límites de la T3:

```
0 < n <= 64
0 < m <= 64
0 < limit < 256
0 <= color < 9
```

**Comment by rlira2** [comment]
hablando de límites... finalmente que día y a que hora se cierra el plazo para entregar la tarea? Con el plazo extra me perdí...

**Comment by LeFranck** [comment]
+1!

**Comment by Ghoeb** [comment]
El enunciado de la tarea decía Lunes a las 23:59, yo dije que se dan dos dias adicionales, por lo tanto queda para el miercoles a las 23:59.
