### ISSUE TITLE
Utilidades Matemáticas

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#78]
Para que no se calienten la cabeza con los coeficientes multinomiales y los múltiples factoriales que hay metidos en la combinatoria de la tarea (para hacer la funcion de hash) les subí un módulo de funciones de ayuda.

En particular por ahora están:

```c
src/helper/multinomial.h

/* Calcula el coeficiente multinomial de n sobre k0,k1,...,k7,k8 */
uint64_t multinomial(int n, int k[9]);
```

Esto es para poder obtener una aproximación de la cardinalidad del espacio de búsqueda. Además, para sus necesidades de números enormes escribí

```c
src/helper/primes.h

/* Entrega un arreglo con la descomposición prima de n */
uint8_t*  prime_decomposition(int n); // 0 < n <= 256

/* Entrega la cantidad de elementos que tiene la descomposición prima de n */
uint8_t   prime_decomposition_length(int n); // 0 < n <= 256

```

Esto es para que puedan trabajar con números muy grandes, como cuando tienes 256! / 255!. El resultado es sólo 256, pero si calculas ambos factoriales tu computador explotará antes de llegar a algo. Puedes obtener la descomposición prima de cada uno de ellos y armar un arreglo, y luego simplificarlo con

```c
src/helper/multinomial.h

/* Simplifica los factores en común de dos números dadas sus listas de factores */
void simplify(uint8_t* num, int num_count, uint8_t* den, int den_count);

```

Estas funciones fueron escritas para un proposito muy particular, y pueden no servir para un caso general. Si quieren pueden usar librerías para "numeros grandes" como la _GNU Multi-Precision Bignum Library_ (_GMP_), en caso de necesitar algo más general.

De todos modos, les comenté el código cosa de que sea llegar y llevar. Si ven algo que se ajusta a sus intereses, no tengan miedo de copiarlo y modificarlo. Asegurense de leer la documentación completa en los .h!

Vicho out!

**Comment by Ghoeb** [comment]
Ok, si, si necesitan manejar numeros grandes, definitivamente usen GMP.

Pueden instalarlo en Ubuntu con

```sh
sudo apt-get install libgmp3-dev
```

en Mac OSX con

```sh
brew install gmp
```

y en Windows con @felix91gr 

Para compilarlo deben agregar -lgmp a la variable LIBS en la Makefile:

```sh
LIBS=-lm -lgmp
```

Lo que les interesa es el modulo de enteros multipresición: mpz

Para ver las operaciones revisen la documentación [aquí](https://gmplib.org/manual/Initializing-Integers.html#Initializing-Integers)

Estos números usan un poco de memoria, pero debería ser muchísimo más rápido que trabajar factor por factor.

Cualquier duda sobre como usar la librería preguntenme.

c:

**Comment by felix91gr** [comment]
Para los que están usando Windows: 

GMP ya les viene en la instalación que hicieron en el Tutorial donde instalaron C y GTK.

Así que... compilen! :smiley:

**Comment by Ghoeb** [comment]
De hecho, disculpas, olviden el código que subí, dado por alguna razon lo hice pensando que 64x64 = 256... por lo que no sirve para todos los puzzles.

**Comment by trencoret** [comment]
@Ghoeb Tuve que cambiarme de PC y ahora volvi a mi mac y no me funciona instalar GMP. Hice brew install gmp, y me lo instala bien, pero despues al hacer make file me sale
 `src/main.c:5:10: fatal error: 'gmp.h' file not found
#include <gmp.h>`

Si lo busco `find /usr /opt -name "gmp.h"` me retorna:

`/usr/local/Cellar/gmp/6.1.0/include/gmp.h`

`/usr/local/include/gmp.h`

Estuve buscando un buen rato en google pero no pude solucionarlo, se te ocurre que puede ser mi problema?

Muchas gracias

**Comment by Ghoeb** [comment]
Pero... incluiste el flag de gmp en la makefile?

**Comment by trencoret** [comment]
Si lo inclui, si antes me estaba corriendo bien pero al cambiarme de computador y con el mismo codigo, no me reconoce gmp

**Comment by Ghoeb** [comment]
Pucha... falló brew nomás. Que dice el brew doctor?

**Comment by trencoret** [comment]
Tomass-MacBook-Pro-2:Programa TR$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/man/mann

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Users/TR/anaconda/bin/curl-config
    /Users/TR/anaconda/bin/freetype-config
    /Users/TR/anaconda/bin/libdynd-config
    /Users/TR/anaconda/bin/libpng-config
    /Users/TR/anaconda/bin/libpng16-config
    /Users/TR/anaconda/bin/python3-config
    /Users/TR/anaconda/bin/python3.4-config
    /Users/TR/anaconda/bin/python3.4m-config
    /Users/TR/anaconda/bin/xml2-config
    /Users/TR/anaconda/bin/xslt-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libsqlite3.0.8.6.dylib
    /usr/local/lib/libsqlite3.0.dylib
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/sqlite3.h
    /usr/local/include/sqlite3ext.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libsqlite3.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/sqlite3.pc
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libsqlite3.a
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a

Warning: Your Xcode (6.3.2) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.

**Comment by trencoret** [comment]
Pero es raro porque si me lo pilla instalado, solo como que no lo reconoce cuando lo importo

**Comment by Ghoeb** [comment]
Que tal si pones la ruta completa de gmp en el include?

**Comment by trencoret** [comment]
Pongo esto donde? :D

`/usr/local/Cellar/gmp/6.1.0/include/gmp.h`

Gracias

**Comment by Ghoeb** [comment]
`#include </usr/local/Cellar/gmp/6.1.0/include/gmp.h>`
XD

**Comment by trencoret** [comment]
Me empieza a webiar en el make file 

`gcc -std=c99  -Wall -g ./obj/main.o  -lm -o solver -lgmp`
`ld: library not found for -lgmp`

Que le pongo en vez de?  `LIBS= -lgmp`

**Comment by Ghoeb** [comment]
Corta por lo sano y andate a Ubuntu.
