### ISSUE TITLE
Varias dudas

### ISSUE THREAD

**Issue by josehj** [IIC2133-2016-1/syllabus#79]
Hola
Primero,  ¿como se puede medir la cantidad de memoria usada por el programa?¿ Y cuanto es lo que tenemos que optimizar esta??
Segundo,  no se si es posible que suban un mapa normal,  difícil o lunatic como para ir viendo como escala la complejidad y los tiempos. 
Y último ¿Hay hoy sala de ayuda? 

Gracias

**Comment by felix91gr** [comment]
#### Para medir el uso de memoria

Se sabe con **valgrind**. Por ejemplo, si corro lo que hay en syllabus:

![Un programa siendo corrido con valgrind](https://i.gyazo.com/b7fc730f4f22d29d41a8c63e845fc03d.png)

En la parte en **negrita** se tienen que fijar:

> HEAP SUMMARY:
> > In use at exit: (...)
> > Total heap usage: 1 allocs, 0 frees, **256 bytes allocated**

En este caso, el programa usó 256 bytes de memoria. Nada mal! Pero no está usando una tabla de hash. Esa va a ser la parte que más use memoria en su programa.

#### Para saber cuánto tienes que optimizarla

0. Implementa una solución recursiva, piensa en **DFS o Backtracking** (recuerda acotar la profundidad según el parámetro en el archivo!). Ve que resuelva los problemas **correctamente**.
1. Implementa luego una lista o una tabla de hash cualquiera para recordar qué estados ya viste y **con qué profundidad**.
2. Una vez que funcione, corre el programa con **valgrind** para saber cuánta memoria estás usando, como vimos recién arriba.
3. Piensa en 2 cosas: **primero**, cómo hacer que el hash sea **perfecto**. Es decir, que cada estado tenga un hash único, que ningún otro estado tiene. Para ello piensa en qué fichas hay de cada color en el tablero y qué dimensiones tiene el tablero. **Segundo**, piensa en cómo se acota la función de hash por el hecho de que algunas filas y columnas **no se mueven**.
4. Ahora sabes qué tan óptima puede ser la tabla en uso de espacio. Impleméntala y la diferencia en uso de memoria con la solución anterior es la mejora concreta.

#### Mapas

Vicho está trabajando ahora en los mapas Normal.

Los mapas para esta tarea debieran ser muchísimo más fáciles de construir que los de la T2, así que espero que los podamos tener mucho antes listos.

#### Sala de ayuda

Hay sala de ayuda. Debiera ir Vicho al menos. Yo estoy con mucha pega, no sé si alcance a ir.

**Comment by Ghoeb** [comment]
El puntaje de leaks será asignado de la siguiente manera:

1 - (bytes in use at exit)/(bytes allocated)

En el caso del ejemplo, el puntaje por contener los leaks es 0.
Si devuelves el 100% de la memoria que pides, entonces tienes el 100% del puntaje por contener leaks.

**Comment by rlira2** [comment]
El código base del watcher y helper no tiene bytes allocated? porque me aparecen 256 bytes que faltan por liberar y creo que no son de mi codigo, ya que si corro el código base de syllabus tambien están. ¿como puedo confirmar esto?

**Comment by felix91gr** [comment]
Pregunta: La ventana del watcher se cierra sola o la tienes que cerrar a mano?

Si sucede esto, me parece que hay una parte del watcher que no se termina de ejecutar.

En todo caso, baja de nuevo el código de syllabus y ve cómo te anda usando la carpeta entera (Programa) tal como viene. Puede que sea algo del Makefile que cambió.

Dime los resultados que obtienes :)
