### ISSUE TITLE
Problema GTK con Xcode

### ISSUE THREAD

**Issue by trencoret** [IIC2133-2016-1/syllabus#8]
Hola, instale el GTK como salia en la guia (si lo corro de nuevo me dice que ya esta instalado). Si  corro los ejemplos por terminal no me da error. El problema esta cuando quiero usar Xcode no me reconoce la libreria de gtk. Trate de instalar jhbuild y luego de bajarmelo no me funciono mucho.

Alguien con el mismo error? 

Muchas gracias

**Comment by Ghoeb** [comment]
Bueno por eso estamos trabajando en Atom + Terminal. De todos modos, que significa que no te lo reconoce? El editor de texto reclama o se niega a compilar?

**Comment by trencoret** [comment]
Es para no tener que estar haciendole el make todo el rato, cuando le ponemos run al xcode te lo genera solo y asi puedes ir como debugeando mas rapido. El Atom te deja compilarlo o correrlo del mismo?

Digo que no me lo reconoce al momento de hacerle el run en xcode me tira "'gtk/gtk.h' file not found" que es el mismo error que te tira cuando no lo tienes instalado. Estuve googleando un buen rato y era problema con compatibilizar xcode o compiladores con gtk, pero no pude solucionarlo

**Comment by Ghoeb** [comment]
Tendrías que configurar xcode para que sea capaz de compilarlo, pero como estamos usando el codigo eso no necesariamente sería mas rápido. En general esta estructura de programas con código compartido no se usa, este es un caso muy particular para el cual las IDEs no están preparadas: esa Makefile que les pasé esta preparada cuidadosamente para este propósito.

No sé de paquetes para correr código C en Atom, ya que compilar y ejecutar son dos cosas separadas. Quizas haya pero tendrás que buscartelo tú...

De todos modos, puedes trabajar solo lo de tu código en xCode, ya que lo que tendrías que debugear es tu programa, y no el Watcher, y para compilar ese no necesitas configurar nada especial.

**Comment by trencoret** [comment]
si, prefiero partir con la tarea a que quedarme pegado con el problema. Si, usaria xcode para mi programa no mas porque Watcher y el resto viene listo

**Comment by trencoret** [comment]
Muchas gracias por la ayuda igual :)
