### ISSUE TITLE
realloc() : invalid next size

### ISSUE THREAD

**Issue by flargofelix** [IIC2133-2016-1/syllabus#80]
Hola!
Estoy teniendo problemas con realloc. 
Para guardar mis estados que ya revisé creo un array grande. Cada cierto tiempo es necesario agrandarlo. Para eso el plan es usar realloc.
Tengo el array de estados uint_8*** checked_before y para agrandarlo llamo a 
checked_before= realloc(checked_before, nuevo_largo);
Para el x, el pebble y logra hacerlo dos veces y se cae a la tercera iteración.
Busque en stackoverflow y lo que indican es que retorna un puntero null si no logra reasignar la memoria. En este caso se cae antes de eso. Alguna idea de que puede ser?
Gracias!

**Comment by Ghoeb** [comment]
No se. Esto te pasa incluso para los puzzles simples?

**Comment by flargofelix** [comment]
Afirmativo
Lo que hice ahora(no es lo más bello) es simplemente crear un array gigantesco al comienzo.

**Comment by Ghoeb** [comment]
Y con eso te funciona? :S

**Comment by Ghoeb** [comment]
Recuerda que solo los Easy estan pensados para poder resolverlos con un arreglo, así que no te compliques respecto a eso y una vez que tengas confirmado que tu busqueda funciona bien pasar a implementar una tabla de hash.

**Comment by flargofelix** [comment]
ok!
