### ISSUE TITLE
Duda con malloc

### ISSUE THREAD

**Issue by diesmori** [IIC2133-2016-1/syllabus#81]
Hola! Intento hacer `uint8_t* algo = (uint8_t *) malloc(sizeof(uint8_t) * cantidad);` y me arroja violación de segmento.
En la tarea anterior podía hacer cosas de ese estilo sin mayor problema.

**Comment by diesmori** [comment]
Tendrá relación con que hago esa línea entre dos fscanf de la misma línea del archivo? En particular capturo la cantidad de columnas activas, luego hago el `malloc` y luego sigo capturando los demás números de la fila.

**Comment by Ghoeb** [comment]
Como estás inicialiando `cantidad` ? Por cierto, el cast que estás haciendo no es necesario.

**Comment by diesmori** [comment]
`cantidad` está en `uint8_t`. Creo que es porque lo hago dentro del fopen.

**Comment by Ghoeb** [comment]
Pero como es que le asignas un valor?

**Comment by diesmori** [comment]
`uint8_t cantidad;
fscanf(f, "%hhu", &cantidad);`

Y luego lo uso en el `malloc`. También probé con un número arbitrario hardcodeado :/
Gracias por tu ayuda hasta ahora!

**Comment by Ghoeb** [comment]
Qué dice valgrind al respecto?

**Comment by diesmori** [comment]
Antes de ver Valgrind probe un par de cosas que me han dado resultado:
Antes de hacer `malloc` leí todo lo necesario y luego cerré con `fclose`. Luego hice todos los `malloc` que necesitaba y volví a leer con otro `fopen` para seguir rescatando datos. Finalmente cerré con un segundo `fclose` y todo resultó de maravilla.

TL;DR evitar mezclar `malloc` con `fopen`

**Comment by Ghoeb** [comment]
Eso no es normal, pero si te funciona, OK.
