### ISSUE TITLE
Duda con Include Guard

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#82]
Hola!
Estoy teniendo problemas de conflictos entre los *#include*, por lo que el programa no compila. Tengo tres archivos que se incluyen entre ellos y no he encontrado como solucionarlo.
He usado _H y _H_INCLUDE para la definición de los archivos .h con conflictos, pero no han dado resultado.
Me podrían ayudar? Alguien ha tenido el mismo problema y lo solucionó?
Muchas gracias!

**Comment by Ghoeb** [comment]
Cuando haces `#include` básicamente copias el contenido entero del archivo, el compilador une todos los archivos que se importan entre ellos y los convierte en un solo archivo grande de código, llamada _compile unit_. El problema es que el compilador va a explotar si una misma función está definida dos veces (no puede revisar si es algorítmicamente equivalente)

Por lo tanto, se usan directivas de preprocesador para evitar que un mismo archivo aparezca dos veces:

"si ya incluiste este archivo, no lo vuelvas a incluir"

Por eso los .h (que son los que deberías andar importando) se encuentran envueltos en el "include guard":

```c

/* Si no hay definida una variable llamada ARCHIVO_A_INCLUIR_NUMERO_6 */
#ifndef ARCHIVO_A_INCLUIR_NUMERO_6
/* La definimos (sin valor) */
#define ARCHIVO_A_INCLUIR_NUMERO_6

/* Funciones y structs */

/* Fin del if */
#endif

```

Eso se encarga de que ese archivo sea copiado y pegado solo una vez en un grupo de archivos que se importan entre si: la proxima vez que lea el if no entrará.

Vas a tener problemas si en una misma unidad, dos archivos hacen _guard_ sobre la misma variable, ya que se te va a haber definido al importar el primero, y al importar el segundo no entrará al if por lo que no lo importará.

Me da la impresión de que tu problema va mas allá de los guard. Por la forma en la que trabaja el compilador, **no puedes tener dependencias cíclicas**: si no usas los guards los archivos se importan recursivamente hasta la muerte, y si los usas alguno de esos archivos se quedará sin el codigo que necesita para funcionar. El mismo Atom debería colapsar si lo tratas de hacer. Echale una mirada a ver si es eso.

Saludos

**Comment by estebanmino** [comment]
Sí, de hecho lo tengo definido como tu dices, lo que pasa es que tengo 3 archivos, "hashtable.h", "puzzle.h" y "puzzle_list.h".

Donde en puzzle está mi "struct" que quiero hashear, en *puzzlelist.h* está la struct de una lista de structs puzzle por lo que llama a *puzzle.h*, y en *hashtable.h* está el struct de la tabla de hash que tiene *puzzlelists* para manejar colisiones,  archivo que es incluido además por *puzzle.h*. Siendo estos archivos parte de la primera versión de mi tabla de hash para la tarea.

Estoy pensando simplemente en unir dos archivos en uno "a mano", pero quería saber si había una solución mas inteligente para esto. O tal vez como lo estoy pensando sea muy enredado.

Gracias por la respuesta!

**Comment by Ghoeb** [comment]
Si haces bien los guards no debería haber mayores problemas... pero hacer merge a mano no es una locura, si esa es tu pregunta :P
