### ISSUE TITLE
Duda con ranking lexicografico

### ISSUE THREAD

**Issue by trencoret** [IIC2133-2016-1/syllabus#84]
Hola, estoy intentando hacer la tabla de hash, sin embargo sigo con problemas en el analisis para sacar el ranking lexicografico. Mi problema es que no se como darles rapidamente un valor a cada estado sin preprocesar todos los estados antes (cosa que me toma mucho tiempo en el programa debido a la cantidad de estados). 
Gracias

**Comment by felix91gr** [comment]
Analiza el espacio de estados. Piensa en lo siguiente:

Tengo una máquina tragamonedas de 4 ruedas. Jugando me doy cuenta de que
cada rueda tiene 10 símbolos distintos, repetidos o no.

Un estado de la máquina se representa por la rotación que hay en cada
rueda. Pero lo que quiero en particular es una función de hash que me
permita identificar sólo la línea de al medio, que me muestra 4 símbolos.

Cómo lo hasheo?
Bueno, son 4 símbolos, de 10 distintos.
Por lo tanto puedo representar este estado como un vector con el índice de
cada símbolo: (a, b, c, d).

Por ejemplo un estado puede ser (0, 0, 2, 3) o (9, 8, 3, 1).

Cómo hasheamos esto? Yo quiero un número.

Podemos aprovechar que son 4 números en base 10 y convertir a uno en las
unidades, otro en las decenas, otro en centenas, etc.

Así, el estado (0, 0, 2, 3) se puede convertir en el "23" o en el "2300" o
en quizás "320". Hay que fijar una convención.

Entonces haré que mi hash sea a x 1000 + b x 100 + c x 10 + d.

Ahora ese estado tiene 1 sólo hash: 23.

Y cada estado tiene un hash único también. Wohoo!

**Comment by Ghoeb** [comment]
Esta tarea te exige hacer busqueda sobre el espacio de estados: generar todos los posibles estados es demasiado!

Por lo mismo, debes ir generando los estados a medida que los ves: dado el limite de pasos, la cantidad de estados alcanzables es sólo una pequeña fracción de la cantidad total de estados.

**Comment by trencoret** [comment]
perfecto, pero por ejemplo, si tengo un limite de 5 y tengo 2 filas activas y 2 columnas activas, tendria (2*(filas_activas+columnas_activas)^5) estados alcanzables o no? Igual esto genera una lista gigante para el hashing, hay algun espacio maximo para el stack? porque por default son 8MB o algo asi y si no lo agrando no logro generar la memoria (solo para la lista, sin procesar los estados)

**Comment by Ghoeb** [comment]
piensa en el puzzle easy/basic. Hay realmente tantos estados distintos? O se empiezan a repetir?

**Comment by trencoret** [comment]
si se repiten claramente, de hecho podriamos decir que cada vez que ocurre una operacion contraria (L1 R1) se vuelve a un estado ya visitado, al igual que al ejecutar la cantidad de filas o columnas seguidas una operacion (L1 L1 L1, por ejemplo, en una matriz de 3 columnas). Sin embargo, no logro encontrar una expresion matematica para expresar esto, estoy un poco oxidado en proba parece jaja. Ademas, es posible seguir reduciendo la cantidad de estados?

**Comment by trencoret** [comment]
Ya entiendo el punto, entonces si tengo la matriz:
0 0 1
2 0 1
0 1 2
Tendria como base (9!)/(4!3!2!) estados
Pero ademas, al tener solo algunas filas o columnas activas, reduzco la expresion solo a los elementos que pueden cambiar debido a esta combinacion de filas/columnas que se pueden operar
Por ejemplo si fuera solo la fila y columna 0 la que se pueden mover, tendriamos 5!/3!. Mi problema es como expresar esto matematicamente para cualquier matriz dada, estoy un poco oxidado en proba jaja

**Comment by Ghoeb** [comment]
Recuerda que el ranking lexicografico trabaja sobre una secuencia de valores, como un string. Si solo mueves la fila y columna 0, entonces el ranking siempre lo vas a sacar sobre 

```
{M[0,0], M[0,1], M[0,2], M[1,0], M[2,0]}
```

(Eso a alto nivel. Ahi ve como expresarlo en C)
