### ISSUE TITLE
Desglose informe T3

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#85]
Ok, aqui les va lo que se espera de su informe

* Qué algoritmo de búsqueda usaste y por qué
 * Explica como aplicaste ese algoritmo al problema, y que propiedades del algoritmo son las que lo hacen una buena elección para el problema. Si tu algoritmo usa heurísticas, se espera que las expliques aquí.
* Qué tipo de tabla de hash usaste y por qué
 * Dentro de las distintas formas de manejar colisiones, cual escogiste. Qué propiedades de ese método son las que sirven para este problema en particular. Qué es lo que se está guardando efectivamente en la tabla y por qué.
* La función de hash que diseñaste. De ella deberás
 * Explicar su razonamiento y sobre que datos trabaja
 * Calcular su recorrido (o explicar de donde viene)
   * Se te evaluará según el recorrido de tu función y la cardinalidad de este
 * Calcular su complejidad
   * Se te evaluará según la complejidad asintótica en el peor caso ( O( \* ) ) de tu función. Calculala a partir del tiempo de ejecución; reducir las constantes asociadas es una mejora importante y se te evaluará por ello.
 * Enunciar qué propiedades cumple esta función de hash que la hacen útil para este problema
* Análisis de desempeño. Elige tableros representativos de la dificultad más alta que puedas.
 * Compara en 3 tableros la diferencia de tiempo entre usar 
   * Una lista (o arreglo) de estados conocidos
    * Una tabla de hash con tu función de hash
 * Compara en 3 tableros la diferencia en expansiones entre guardar o no los estados conocidos
 * Compara en 1 tablero la tasa de colisiones de tu tabla de hash al variar su tamaño entre 3 largos distintos
* (Bonus) Incluye posibles mejoras interesantes (mejoras a la función de hash tambien valen) al espacio o tiempo aunque no las hayas podido implementar.

La única parte del informe donde debes incluir código es para calcular el tiempo de ejecución de tu función de hash; si incluyes código en otra parte será ignorado y perderás el derecho al bonus de buen uso del espacio y del formato.

Vicho :whale:

**Comment by tumunoz** [comment]
Vicho, una pregunta, las notas de los informes pasado no están todavía cierto? Sería util tener algún tipo de feedback ante de entregar estos...

**Comment by felix91gr** [comment]
No, y lo siento mucho por esto. No los he podido corregir todavía u.u

Pero puedes usar los [informes subidos de la T1](https://github.com/IIC2133-2016-1/syllabus/tree/master/Tareas/Informes%20de%20ejemplo) como referencia (Ackbar, Burro y Jon Snow). Son informes reales y el criterio con el que se corrigieron es el mismo que el criterio con que se corrigen todos :)

**Comment by Ghoeb** [comment]
La verdad es que la corrección de la T2 ha sufrido una serie de contratiempos (que no tienen nada que ver con la tarea en si). No espero que la podamos tener para el viernes.

**Comment by trencoret** [comment]
No entiendo bien la parte de calcular la complejidad de la funcion de hash. 
`Se te evaluará según la complejidad asintótica en el peor caso ( O( * ) ) de tu función. Calculala a partir del tiempo de ejecución; reducir las constantes asociadas es una mejora importante y se te evaluará por ello.`

Como calculo la complejidad asintotica de mi función a partir del tiempo de ejecución? Esta bien si explico que parametros de entrada reduje y que cambios provocaron?

Hice un análisis de desempeño de tiempo con y sin hash en la siguiente pregunta...

Gracias
