### ISSUE TITLE
Duda valgrind

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#86]
Estoy probando mi programa con valgrind, pero para empezar hice un programa muy simple, sin malloc ni free, algo así

    int main(int argc, char* argv[])
    {
        printf("hola\n");
        return 0;
    }

Por lo que tengo entendido, no debería haber memoria asignada, ni nada por el estilo. Pero, esto es lo que me arroja al correrlo con valgrind:

    ==1125== 
    ==1125== HEAP SUMMARY:
    ==1125==     in use at exit: 1,508,377 bytes in 2,575 blocks
    ==1125==   total heap usage: 3,212 allocs, 637 frees, 2,654,257 bytes allocated
    ==1125== 
    ==1125== LEAK SUMMARY:
    ==1125==    definitely lost: 3,368 bytes in 46 blocks
    ==1125==    indirectly lost: 5,240 bytes in 19 blocks
    ==1125==      possibly lost: 21,008 bytes in 168 blocks
    ==1125==    still reachable: 150,200 bytes in 995 blocks
    ==1125==                       of which reachable via heuristic:
    ==1125==                         newarray           : 1,536 bytes in 16 blocks
    ==1125==         suppressed: 1,328,561 bytes in 1,347 blocks
    ==1125== Rerun with --leak-check=full to see details of leaked memory
    ==1125== 
    ==1125== For counts of detected and suppressed errors, rerun with: -v
    ==1125== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 1 from 1)

No tengo idea donde hay 3212 allocs y 637 frees si es que mi programa es solo un `printf`.
¿Hay alguna manera de limpiar o resetear valgrind para que me muestre 0 allocs y 0 frees?

**Comment by Ghoeb** [comment]
Estás en OSX? Yo advertí que en OSX valgrind arroja falsos positivos y que no es trivial manejarlos. Entiendo que hay un archivo por ahi de valgrind para que ignore algunas cosas, pero no se como configurarlo: busca en internet o usa Ubuntu.

**Comment by flizana** [comment]
Tiene que ver con OSX, al correrlo con `--leak-check=full` me arroja errores que tienen que ver con el sistema operativo asignando memoria, no con mi programa. Gracias igual.
