### ISSUE TITLE
Informe Tarea 3

### ISSUE THREAD

**Issue by flizana** [IIC2133-2016-1/syllabus#88]
Estimados ayudantes,

¿Existe la posibilidad de entregar el informe un día después de la entrega tal como en las tareas anteriores, es decir, el jueves a las 23:59? Muchas gracias.

**Comment by gadlewinsohn** [comment]
+1

**Comment by dacasas** [comment]
+1

**Comment by favazquez** [comment]
+1

**Comment by vjgardul** [comment]
+1

**Comment by adelsol1** [comment]
+1

**Comment by felipebaitelman** [comment]
+1

**Comment by Ghoeb** [comment]
No, lo siento. El plazo está ahí para que puedan preparar su I3. Ya les di un dia adicional del conversado, inicialmente era un solo dia extra.

**Comment by vjgardul** [comment]
y q los recojan a primera hora? O:)

**Comment by felix91gr** [comment]
Nope, aprovecha las 3 horas 10 que te quedan ^^

**Comment by jmdelatorre** [comment]
:(

**Comment by felix91gr** [comment]
Bueno, al final lo discutimos los ayudantes y decidimos que vale la pena que entreguen más tarde.

Acuéstense temprano hoy y aprovechen su tiempo para la I3. 
Pueden entregar el **informe** hasta el sábado a las 23:59.

A los que lo entreguen hoy tienen 5 décimas extra en el informe, si sacan sobre 4.
_Ojo: las décimas se juzgan después de entregar todos los bonus y son independientes de todos ellos._

**Comment by dacasas** [comment]
Gracias!!
