### ISSUE TITLE
Problemas grandes

### ISSUE THREAD

**Issue by vjgardul** [IIC2133-2016-1/syllabus#89]
Hola con los problems grandes se me cae al inicializar tableros (o matrices, o nodos o como les llamen). Especificamente tengo un struct board del tipo:

```csharp
typedef struct board {
//cosas
} Board;
```
y cuando lo llamo con malloc me dice que

```csharp
Board *aux = (Board*) malloc(sizeof(Board *));
```
>t3aux(37459,0x100081000) malloc: *** error for object 0x1002005d8: incorrect checksum for freed object - object was probably modified after being freed. *** set a breakpoint in malloc_error_break to debug

**Comment by flizana** [comment]
Según yo deberías hacer `Board *aux = malloc(sizeof(Board));`

**Comment by Ghoeb** [comment]
Lo que dice Fernando es lo correcto. Te falla con eso?

**Comment by vjgardul** [comment]
Si grande fernando  🙌 me siento un noob
