### ISSUE TITLE
Problema corriendo solver y watcher juntos

### ISSUE THREAD

**Issue by trencoret** [IIC2133-2016-1/syllabus#9]
Bajando el programa que subieron, si le hago make y corro el solver ingresandole el archivo de texto corre sin problemas, corro el watcher por separado y tampoco tiene problemas. Cuando los corro juntos ./solver < 1x1.txt | ./watcher se me queda "esperando" a que cierre la pantalla del watcher para terminar de ejecutar el comando y no me corre el solver. Que hacer para que corran los dos juntos? Asi podemos ir probando el codigo y viendo como cambia en el watcher.

Gracias

**Comment by Ghoeb** [comment]
De donde sacaste que el solver no se está ejecutando?

**Comment by trencoret** [comment]
jaja invento mio, como hago para que me muestre todo lo que corrio en la terminal? Asi como lo muestra cuando lo corro solo :)?

**Comment by felix91gr** [comment]
Haz que tu programa guarde el output en un archivo de texto y luego le das ese output al watcher.
Usa estos comandos:

Guarda el output
```bash
./solver > output.txt
```

Carga el output en el watcher
```bash
output.txt > ./watcher
```

Así después puedes mirar qué escribió tu programa :)
Quizás en una futura versión del watcher será posible pedirle que imprima el output en la consola para ayudar.

**Comment by Ghoeb** [comment]
Al usar el pipe ( | ) el watcher lee solo lo que el solver escribió en `stdout`, por lo que si quieres imprimir mensajes de prueba y que aparezcan en consola al correr ambos juntos, usa

```c
fprintf(stderr,"%s\n","Tu mensaje");
```


Para `fprintf` aplican las mismas reglas de parametro que para `printf`. Asi tus mensajes serán escritos en `stderr` por lo que aparecerán en consola. Cuidado que si imprimes a `stdout` y a `stderr` y haces que ambos aparezcan en consola, no necesariamente van a aparecer en el orden que los mandaste a imprimir (dentro de cada stream el orden es correcto, pero al intercalar ambos no puedes asegurarte de que una llamada ocurrio antes o despues que otra)

**Comment by trencoret** [comment]
Muchas gracias vicho!
