### ISSUE TITLE
Los que trabajamos solos, simplemente subimos la tarea al repositorio de siempre?

### ISSUE THREAD

**Issue by jjsotomayor** [IIC2133-2016-1/syllabus#91]
Eso, ¿Usamos el repositorio que nos dieron a principio de semestre?
Pregunto porque en la ayudantia de la tarea dijeron que el repositorio seria distinto, incluso para los que trabajaramos solos.

**Comment by felix91gr** [comment]
Oh. Hmm. Usa el de siempre nomás.

**Comment by felix91gr** [comment]
Si alguien ya estaba usando otro repo, no hay problema tampoco.
