### ISSUE TITLE
Fe de Erratas

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#92]
Corregido error en el enunciado, página 2

_Se busca encontrar el grafo G'(V',E')_

cambiado por

_Se busca encontrar el grafo G'(V,E'), donde E' forma parte de E_

**Comment by Ghoeb** [comment]
Corregida además solución del archivo de ejemplo:

Es
```
0
5
7
```
No 

```
1
3
6
```

**Comment by diesmori** [comment]
Gracias por avisarnos!
A qué se debe la corrección de la solución del ejemplo? Al priorizar la maximización de volúmenes en nodos por sobre la minimización de costos en aristas me da (1,3,6).
Puedes explicarnos cómo has llegado a (0,5,7) o es mucho spoiler?

**Comment by Ghoeb** [comment]
Dime, cual es la suma de los `h` y la suma de los `w` en cada caso?

**Comment by diesmori** [comment]
Para (0,5,7): sum(h)= 190. sum(w)= 190.
Para (1,3,6): sum(h)= 240. sum(w)= 270.

Ratio (0,5,7): h/w= 1
Ratio (1,3,6): h/w= 0,889

Es eso entonces? Me parece razonable, a pesar de ser menos volumen en (0,5,7) está minimizando el costo de las tuberías.

**Comment by Ghoeb** [comment]
No, la suma de los h es 200 en ambos casos, y es lo más alto que puede ser, mientras que las tuberías son más baratas en (0,5,7). Esta solución es óptima. Ese ratio que pones no es relevante ya que maximizar la capacidad es la prioridad N° 1, y además puedes obtener el mismo ratio con una solución mala que con una solución buena... no es indicador de nada.

Dado que se pide que primero optimices capacidad y luego costo, el puntaje que puedas obtener por optimizar costo habiendo optimizado mal capacidad será muy reducido, sino nulo.

**Comment by diesmori** [comment]
Aaah, por la capacidad de la fábrica!
Todo aclarado, muchas gracias.
