### ISSUE TITLE
Ayudantía Lunes 20

### ISSUE THREAD

**Issue by alopez7** [IIC2133-2016-1/syllabus#93]
¿Hay ayudantía el lunes? 
Si hay, ¿Es de la tarea?

**Comment by Ghoeb** [comment]
No, lo que haya para trabajar en la tarea será los viernes en las salas de ayuda.

**Comment by jjsotomayor** [comment]
A que hora van a estar el viernes??

**Comment by Ghoeb** [comment]
Ahora?

2016-06-17 15:59 GMT-03:00 jjsotomayor <notifications@github.com>:

> A que hora van a estar el viernes??
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/IIC2133-2016-1/syllabus/issues/93#issuecomment-226853414>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFElCeYE3pKbe1v0anI5VvzMp_pfJg7Rks5qMu6AgaJpZM4I3-Jp>
> .
>



-- 
*Vicente Errázuriz Quiroga*
