### ISSUE TITLE
Capacidad de tuberías

### ISSUE THREAD

**Issue by diesmori** [IIC2133-2016-1/syllabus#94]
Hola! Quiero aclarar un detalle sobre el conteo de volumen que llega a cada nodo:
Tengo los nodos A, B y C, origen en A, donde están conectados A--->B--->C, y (A,B) tiene capacidad 5 y (B,C) tiene capacidad 8. Si el volumen suministrado a B es 5, el volumen de C es 5 también o entre ambos nodos deben repartirse esos 5? El sentido común me dice que deben repartirse, pero creo que en el enunciado esto queda medio gris.
Gracias!

**Comment by Ghoeb** [comment]
El problema no trabaja con el volumen suministrado ni flujo, dado que técnicamente cada una de las estaciones es un sumidero y a la vez un origen, y no quiero entrar en eso. 

La capacidad de una estación representa cual sería el máximo output que podría otorgar una estación en un momento dado, dejando de lado la sincronización entre estaciones: claramente si se quisiera sacar _Slurm_ de todas las estaciones simultáneamente a máxima capacidad la red colapsaría, pero lo que se te pide es una cota superior, básicamente dejar a todas las estaciones lo más capaces posibles pero disminuyendo el costo de mantención de la red. Quizas en el problema real haya que tener más cosas en mente a la hora de optimizar, pero aqui estamos trabajando con la version simple.


Volviendo al problema: en la página 2  están las fórmulas que indican como calcular la capacidad de una estación, y si hay alguna parte que queda ambigua porfavor dime cual es para corregirla:

Siguiendo tu ejemplo:

La ruta de B a A consiste en unicamente (A,B), y w((A,B)) = 5
La ruta de C a A consiste en {(A,B),(B,C)}, y w((B,C)) = 8.

h(A) = k

h(B) = min(k, w((A,B))) = min(k,5)

h(C) = min(k, w((A,B)), w((B,C))) = min(k,5,8) = min(k,5)

Asi que si k >= 5, entonces h(B) = 5 y h(C) = 5
Si k < 5, entonces h(B) = k y h(C) = k

Saludos

**Comment by diesmori** [comment]
Muchas gracias, Vicente. Me queda claro.
