### ISSUE TITLE
Prioridades Tarea 4

### ISSUE THREAD

**Issue by alopez7** [IIC2133-2016-1/syllabus#96]
¿Se debe priorizar aumentar el flujo o aminorar los costos?
Tengo un ejemplo:
nodos 0, 1, 2, y el 0 es el origen
k = 50
w(0,1) = 40
w(1,2) = 40
w(0,2) = 60
Si elijo las rutas (0,1) y (2,1) tengo Suma de h() = 80, y suma de w() = 130
En cambio si elijo las rutas (0,2) y (2,1) me da Suma de h() = 100 y suma de w() = 140

En un caso minimizo el w y en otro caso maximizo el h, pero no puedo hacer ambos

**Comment by Ghoeb** [comment]
La idea es maximizar h, y una vez que hagas eso, minimizar el w. Puedes tener aristas que te mantengan constante el h, la idea sería entonces entre esas elegir la más chica para minimizar el w, no?

**Comment by alopez7** [comment]
Gracias
