### ISSUE TITLE
Referencias a estructuras

### ISSUE THREAD

**Issue by alopez7** [IIC2133-2016-1/syllabus#97]
Hola, tengo una duda de como hacer algo en c.
Lo que pasa es que quiero crear una estructura lista para llevar aristas, una estructura nodo, y otra arista.
Un nodo tiene punteros a listas de aristas, las listas de aristas tienen punteros a aristas, y las aristas tienen punteros a nodos.
Además, hay funciones en la estructura nodo que necesitan aristas, y muchos enredos así.
La cosa es que no se como referenciar estructuras que aún no he creado, porque si creo la estructura nodo primero, me va a alegar que no existe la estructura lista, y así.

**Comment by Ghoeb** [comment]
Lo que pasa es que el compilador parsea el archivo de arriba hacia abajo, y para él solo existe lo que ha visto. Lo único que necesitas para poder referenciar una estructura o una función es saber que existe algo con ese nombre. Por eso al definir las firmas de las funciones en el `.h` o al principio del `.c` luego las puedes usar en todo el archivo correspondiente.

Sino pasa esto
```c

void foo(int a)
{
     /* Error de compilacion: bar no está definido */
     bar(a); 
}

void bar(int a)
{
     /* Do something */
}
```

Pero puedes corregirlo declarando la firma de `bar()` antes

```c

/* Definimos que existe una función void que recibe un int como parámetro */
void bar(int); 
/* Ponerle nombre al parámetro también es correcto */
/* void bar(int a); */

void foo(int a)
{
     /* Ahora podemos compilar porque sabemos que existe esta función. */
     bar(a);
}

/* Cuando el compilador pase por aquí recién sabrá que es lo que hace esta función */
void bar(int a)
{
     /* Do something */
}
```

Para los `structs` es lo mismo:

````c
/* Definimos que existen structs con estos nombres */
struct foo;
struct bar;


/* Y ahora se pueden referenciar entre ellos */
struct foo
{
     struct bar* rab; // No importa no saber lo que es un bar, los punteros son punteros
};

struct bar
{
     struct foo* oof;
};


```
