### ISSUE TITLE
Acerca de los tests

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-2016-1/syllabus#98]
Les subí un generador de tests ya que los archivos pesan much sino. Recibe los siguientes parametros

1) La cantidad aproximada de vertices
2) La cantidad aproximada de aristas
3) Una semilla aleatoria

Los easy tienen del orden de V = 1000, E = 10000
Los normal tienen del orden de V = 10000, E = 100000
Los hard tienen del orden de V = 100000, E = 1000000
Los lunatic tienen del orden de... más que eso. Ya les daré la cantidad específica.

Ejemplo para generar un hard:

```sh
./generator 100000 1000000 1313 > hard_ejemplo.txt
```

Espero que sus tareas sean capaces de resolver los tests en menos de 10 segundos en mi computador.

Saludos :whale:

**Comment by adelsol1** [comment]
Hola! Existe alguna forma de comprobar que nuestros resultados son mas o menos correctos? Cómo se calculará esto?

**Comment by Ghoeb** [comment]
No! La idea es que traten de maximizar la suma de los h todo lo posible (calcular cual es el máximo o una aproximación de este no debería ser dificil, se hace con un algoritmo visto en clases) y luego de eso minimizar todo lo posible la suma de los w.

Yo tengo dos soluciones: 

La primera se preocupa solo de maximizar la suma de h. Si tu suma de h es igual a esta o mejor, tienes asegurado el 4 para ese test.

La segunda maximiza el h, pero además minimiza el w. Si tus valores son igual o mejores que eso, entonces tienes asegurado el 7 para ese test. (Si es mejor tendrás más que un 7).

Dado que la prioridad es maximizar el h y luego minimizar el w, si tu w es bajo pero tu h no es lo suficientemente alto, no aseguro que tengas mucho puntaje.

Eres libre de comparar tus resultados con tus compañeros usando algún test pequeño. La dificultad de los tests que les paso yo va mas por un tema de orden de ejecución: no me sirve que tu algoritmo sea cuadrático, por ejemplo.

**Comment by adelsol1** [comment]
Buena :).. Otra duda.. genere un test "easy" de 100 nodos y me arma el problema con 96 aristas (con lo que es imposible llegar a todos los nodos..  :/
Lo genere con : `./generator 100 100 2311 > easy.txt` , puse algo mal.. o que numero aleatoreo deberia poner.?

**Comment by Ghoeb** [comment]
El parámetro que recibe el programa es "el orden" de los valores. Si le dice 100 te va a poner entre 90 y 110 aristas. Esto para dar mas aleatoreidad a los test. Con E = 2V debería andar bien

**Comment by alopez7** [comment]
Hola, el codigo generador me acaba de tirar un error. El input fue:
./generador 10000 100000 0 > normal1.txt
y el error es:
Error in "./generator": double free or corruption...

**Comment by Ghoeb** [comment]
Uy, curioso, que pasa si le das otra semilla?

**Comment by alopez7** [comment]
Con algunas semillas se cae y con otras no

2016-06-23 4:03 GMT-04:00 Vicente Errázuriz <notifications@github.com>:

**Comment by LeFranck** [comment]
Hola, el generador de repente da más aristas de las que dice que dará. Al hacer ./generator 1000 1000 1 > easy.txt me dice E 887, pero el archivo tiene en realidad 1119 aristas.

**Comment by Ghoeb** [comment]
Por favor no abusen del generador... está pensado para que la cantidad de aristas sea significativamente superior a la cantidad de vértices :cry:

**Comment by estebanmino** [comment]
Hola! Dos preguntas,
1. De que orden serán los lunatic al final?
2. El tiempo que esperas que sea en menos de 10 segundos es el de computación no el de "printeo" de aristas, verdad?
Gracias!

**Comment by Ghoeb** [comment]
Aun no lo he podido ver en detalle pero será al menos un orden de magnitud mas grande que los hard, en vertices, o aristas, o ambos. 

El tiempo de printeo de las aristas es negligible ya que lo redirigiré a un archivo para poder leerlo, pero por supuesto que incluye todo.
