### ISSUE TITLE
Error al compilar Tarea 4

### ISSUE THREAD

**Issue by estebanmino** [IIC2133-2016-1/syllabus#99]
Hola!

Estoy teniendo problemas para compilar, incluyendo el código base de *generator*. He probado con las tareas anteriores por si algo cambió en mi computador y no tengo errores.

El error que tengo es 

```
esteban@efmino:~/Desktop/syllabus-IIC2133/Tareas/Tarea 4/Programa$ make
compilado obj/generator/generator.o
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [generator] Error 1
esteban@efmino:~/Desktop/syllabus-IIC2133/Tareas/Tarea 4/Programa$ 
```

Que puedo hacer?

Gracias!

**Comment by Ghoeb** [comment]
Ah, esa Makefile la tome de la de la T3, pero aqui no estamos usando GMP asique puedes borrar el flag `-lgmp`.

Debería quedar

````Makefile
LIBS=-lm
```

**Comment by estebanmino** [comment]
Funcionó, gracias
